### ISSUE TITLE
Rationale for excluding cloneable

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#24]
#### NFT Type

Categorized outputs may encode one of 5 NFT states:

- `NFT_NULL = 0x00`, *(b00000000)*
- `NFT_TRANSFER = 0x3F`, *(b00111111)* ("no capability", "immutable")
- `NFT_EDIT = 0x7F`, *(b10111111)* ("mutable")
- `NFT_CLONE = 0xBF`, *(b01111111)*
- `NFT_MINT = 0xFF`. *(b11111111)*

All other values are reserved and reading a reserved value will immediately fail the transaction.

**Comment by A60AB5450353F40E** [comment]
There's no reason to use up more "bit space" than needed by picking aesthetic values like ff, ee, 11.

This encoding allow us to use both numerical comparison and bitwise operators to check for NFT capability, and is extensible.

**Comment by cculianu** [comment]
I agree I would have preferred bits.  Question: Why set the low order nibble's bits all high for NFT?

Why not just do this?

- `NFT_Fungible` = 0x00, (b00000000)
- `NFT_Immutable`= 0x1, (b00000001) 
- `NFT_Mutable` = 0x3, (b00000011)
- `NFT_MINT` = 0x7, (b00000111)

**Comment by A60AB5450353F40E** [comment]
To have some logical consistency. Even if we don't specify more capability granularity, we may do so in the future by subtraction from the "max" - the mint. The mint allows NFT to do anything, can't be more capable than that so 0xff. The NULL is the opposite the nft doesn't even exist, can't be more incapable than that so 0x00. In-between values are granularity in limiting what a NFT can do. Take out a bit, you remove some ability - like when you define mutable, you remove the ability to make multiple outputs. With immutable, you also remove the ability to edit the message. But we could remove more abilities from those that an NFT has by default, that can't be toggled off with current spec:
- ability to "edit" the script field
- ability to take FTs in/out
- ability to take sats in/out

**Comment by cculianu** [comment]
I see. Well then I can see why you'd want "space" in between NFT_Mutable and NFT_Mint.. But isn't NFT_Immutable just about the lowest-level NFT?  Can't that be 0x1?  Why all the 1's in the low order? 

I still don't really get it.  Also I am not sure what script field you refer to to be editing?? Or what it means to take out FT's or take them in?  Or to take sats in/out?  Not really sure but I am assuming some more sophisticated future consensus rules for more complex behavior?

Regardless I do understand the philosophy of what you suggest...I just still don't get why low-order nibble would always be 11111 ..  like even the most basic NFT, just the transfer (immutable) type still has 1111 as the low-order nibble, like it can't get lower than simple transfer, can it? 

Like to me it would make sense to do:

- `NFT_None` = 0x00, (b00000000)
- `NFT_Immutable`= 0x1, (b00000001) 
- `NFT_Mutable` = 0x3, (b00011111)
- `NFT_Mint` = 0x7, (b11111111)

Maybe?  You know what  I mean?

**Comment by A60AB5450353F40E** [comment]
>But isn't NFT_Immutable just about the lowest-level NFT?

The currently proposed "immutability" applies only to the the "nft message" and nothing else but there are other parts of the UTXO tied to the NFT that could be made immutable: sat amount, ft amount, locking bytecode. I'm not proposing we expose additional granularity, just sharing my thinking here.

With this in mind, the most limited transfer would be the transfer of exact same state of the UTXO, that would be a 0x01. Changing the satoshi value does more than just transfer - it also takes in those sats, changing the ft amount does the same, sending it to another address also does more - it changes the value of locking script field.

Min (no nft) and max (mint, can do anything) are concepts well defined, but this space in-between requires a crystal ball and depends on your mental model too, but in any case we could still later add granularity by interpreting the bits as "deny capability X" instead of "has capability X".

With that in mind, we could do with:

- `NFT_NULL = 0x00`, *(b00000000)*
- `NFT_TRANSFER = 0x03`, *(b00000011)* ("no capability", "immutable")
- `NFT_EDIT = 0x07`, *(b00000111)* ("mutable")
- `NFT_CLONE = 0x0B`, *(b00001011)* - I'd reserve this slot, but we don't need to enable this one.
- `NFT_MINT = 0x0F`. *(b00001111)*

This way capabilities would fit onto 1-byte `OP_N` number push opcodes which is convenient when contracts have to verify the capability, and we have 2 bits (3 if with "clone") to define some future "has capability X" and 4 bits to encode "deny capability X".

**Comment by cculianu** [comment]
> it also takes in those sats, changing the ft amount does the same, sending it to another address also does more - it changes the value of locking script field.

Aha, I see yes.

>  but this space in-between requires a crystal ball and depends on your mental model too, but in any case we could still later add granularity by interpreting the bits as "deny capability X" instead of "has capability X".

True, that is the rub.  Well now that you clarified it can get lower than immutable, I'm ok with the entire nibble being 1's like you initially suggested.  I just didn't understand why that was necessary and I didn't imagine we'd ever want such a restrictive NFT that wants everything or more things "the same".  Fine by me.  Either 0011 or 1111 for NFT_Immutable is fine, or whatever else.

**Comment by bitjson** [comment]
Thanks for the discussion here! 

I appreciate the logical framework you're using to analyze capabilities @A60AB5450353F40E! That's a great way to demonstrate that we've reviewed all of our options and accepted or rejected each. I hadn't been thinking of it that systematically – I'll try to structure a rationale section around that, thanks!

### Token encoding can't be directly upgraded

On planning for future upgrades: I'm afraid these prefix-based transaction format upgrades are only backwards-compatible because existing parsers expect arbitrary opcodes in the space we're using. Once we define an encoding for a prefix, it's no longer possible to upgrade that encoding in a backwards-compatible way. So future upgrades are more likely to either 1) simply use a new prefix or 2) actually upgrade the whole transaction format with a new version number (more detail in https://github.com/bitjson/cashtokens/issues/7#issuecomment-1065480447). I think that means that even if we left a sort of "upgradable space" in the encoding for capabilities, it would still end up unused.

The other messy issue with planning for upgrades that add capabilities: we can't safely modify the output of a deployed opcode unless we are:

- changing a failure to succeed (a "hard fork", but safe for other contracts if the new behavior is itself safe, e.g. backwards-compatible schnorr support, bigger numbers, new/re-enabled opcodes)
- changing a successful evaluation to a failure (a "soft fork", but unsafe for contracts unless another input could still produce the previous behavior, e.g. malleability patches)

Other than those cases, I'm fairly certain there's no safe way to even slightly modify the expected output of an existing opcode without "breaking the API" exposed to contracts.

E.g. even if we had a simple `OP_OUTPUT_TOKEN_CAPABILITY` that accepted an index and returned one of these above numbers (`0`, `3`, `7`, `15`), while many contracts would be written to validate results by direct comparison (`<N> OP_OUTPUT_TOKEN_CAPABILITY <3> OP_EQUAL`), almost all byte-efficient contracts with multiple codepaths (based on capability) would be broken unpredictably: a contract might perform some validation for `<=3`, some for 7, and an `OP_ELSE` branch for the `15`. If an upgrade slips a new `14` result into the set of possible results, it breaks the API used by that contract and produces a serious vulnerability. (More discussion: [Including Capabilities in Token Category Inspection Operations](https://github.com/bitjson/cashtokens/tree/f8b500a051f82d42dbf9e9e890bc6cdc14592307#including-capabilities-in-token-category-inspection-operations), and aside: if we had only MATCH/CASE instead of IF/ELSE, modifying results might be safe, but for Bitcoin(Cash) the die is cast.)

I think what all this really means: we get one shot. We should try our best to get it perfect the first time. If future proposals realize we missed something important enough to be worth the effort of an upgrade, they'll have to contend with exposing the new functionality in a way that does not break contracts (and if desired, also doesn't break transaction parsers, i.e. new output prefixes).

Fortunately the VM is already incredibly flexible – even if e.g. we missed the idea of a `mutable` capability, we could have emulated it with both [bounded loops](https://github.com/bitjson/bch-loops) and a common standard for designating a minting token as "only mutable" so contracts that aren't co-developed can coordinate to avoid their looping "mutable validation" from conflicting, e.g. by using a few more bytes to check specifically that "no outputs create tokens of the relevant category" rather than just checking that "no outputs create unexpected tokens". (Obviously, adding a `mutable` capability now is far simpler and more efficient in terms of transaction sizes.)

---

On some of the specific possible capabilities:

### Cloneable capability

I struggled the most with the `cloneable` capability because it (like `mutable`) is relatively expensive to emulate (so if needed, it would belong in the protocol). But I think we can actually demonstrate that [cloneable would be a "code smell" in contracts](https://github.com/bitjson/cashtokens/issues/7#issuecomment-1158528229), and would just end up adding complexity to the protocol without practical use. (Of course, like the approach described above with `mutable`, there are other strategies for accomplishing the cloneable behavior if some significant change to the VM/UTXO model makes cloneable useful.)

---

I need to think more about the possible capabilities revealed by @A60AB5450353F40E's framework – immutable locking bytecode, FT amount, satoshis, etc. My initial reaction is that these are well served by transaction introspection operations, but we should either include or have solid reasoning for excluding each. (I'll work on an exhaustive `Selection of Token Capabilities` rationale section.)

### Immutable locking bytecode capability

Preventing locking bytecode from being modified seems most interesting – that's a very common use case in covenants, and now that covenants can store state in commitments, avoiding modifications to locking bytecode can sometimes save on transaction overhead (depends on the contract).

Thinking through it though – it's already very inexpensive to perform the same validation in the contract itself `OP_INPUTINDEX OP_UTXOBYTECODE <N> OP_OUTPUTBYTECODE OP_EQUAL` – typically 5 bytes, whereas adding another capability to also perform this behavior would add quite a bit more protocol complexity around token validation. It may also not be a completely clean complexity-for-optimization tradeoff – if many contracts validate capabilities exhaustively (common for covenants), they end up adding a few more bytes to skip over or handle the added capability, so in total they may need to add 3-5 bytes in another location, in order to "save" those 5 bytes, negating the value of adding the capability at all.

---

Sorry for the length 😅, hopefully the headings make it easier to skim/link.

**Comment by A60AB5450353F40E** [comment]
>Other than those cases, I'm fairly certain there's no safe way to even slightly modify the expected output of an existing opcode without "breaking the API" exposed to contracts.

Yeah, your example demonstrates this well. We can't safely upgrade using the same prefix.

>I think what all this really means: we get one shot. We should try our best to get it perfect the first time. If future proposals realize we missed something important enough to be worth the effort of an upgrade, they'll have to contend with exposing the new functionality in a way that does not break contracts (and if desired, also doesn't break transaction parsers, i.e. **new output prefixes**).

Agreed. This actually adds weight to the "one prefix" design decision. Save the ["codepoint space"](https://github.com/bitjson/cashtokens/issues/27#issuecomment-1178746721) for future upgrades.

>Immutable locking bytecode capability

>Thinking through it though – it's already very inexpensive to perform the same validation in the contract itself OP_INPUTINDEX OP_UTXOBYTECODE <N> OP_OUTPUTBYTECODE OP_EQUAL – typically 5 bytes

It is inexpensive when you already know there can only be one output (NFT is mutable or immutable). However, what if you have a mint you want to keep inside a covenant but make copies? I imagined this capability to be useful in combination with "cloneable". It'd save Script the work of iterating through all the outputs to enforce the Script (and nft commitment) is carried over correctly.

>That's a great way to demonstrate that we've reviewed all of our options and accepted or rejected each. I hadn't been thinking of it that systematically – I'll try to structure a rationale section around that, thanks!

Thanks, yeah I've been searching for a good logical framework to reason about this all, there's more options, I'll try to list them all in the next post.

>E.g. even if we had a simple OP_OUTPUT_TOKEN_CAPABILITY that accepted an index and returned one of these above numbers (0, 3, 7, 15), while many contracts would be written to validate results by direct comparison (<N> OP_OUTPUT_TOKEN_CAPABILITY <3> OP_EQUAL), almost all byte-efficient contracts with multiple codepaths (based on capability) would be broken unpredictably: a contract might perform some validation for <=3, some for 7, and an OP_ELSE branch for the 15. If an upgrade slips a new 14 result into the set of possible results, it breaks the API used by that contract and produces a serious vulnerability.

Yup. But even if we imagine upgrading with a new PFX, I think it'd still be nice to define our capabilities so some API familiarity is preserved. Imagine having  2 flavors of tokens (2 PFXes) but you use a different value to encode a mint...  that would increase the risk of mixing something up when you switch flavors.

**Comment by A60AB5450353F40E** [comment]
>I'll try to list them all in the next post.

The fundamental primitive our blockchain is the TXO. Imagine if our transaction outputs didn't have script and satoshi amount fields - that's the fundamental primitive, just the outpoint ref. with no data (satoshi amount, script) at all. I think @cculianu already has this mental model as I saw him refer to even the satoshi amount as "metadata" :laughing: Some NFT capabilities would make sense even if our UTXOs didn't encode any amounts (allow 0, 1 or many children) which makes me see NFTs as exposing a permission interface for our most fundamental primitive - the TXO.

With that in mind, here's a list:

- Capability to create children (0, 1, many="cloneable"). 0 would mean unspendable
- Capability to "edit" satoshi amount. What would this mean? Because it's a fungible amount it'd make no sense to lock the amount for a single output, but it could lock/unlock some aggregate satoshi amount from being associated with a commitment.
- Capability to edit locking script, would work the same as capability to edit the commitment but combined with "cloneable" would allow splitting the covenant to multiple threads while saving the bytecode needed to verify threads. Combined with "satoshi lock" the threads would have to share the amount inherited from the parent and couldn't release or take in "external" sats.
- Capability to "edit" fungible token amount, similar to "satoshi lock" but with token amounts, would allow to prohibit freedom of movement FTs now have by default, so you could sub-divide the FT supply using NFT commitments
- Capability to edit the commitment
- Capability to pass on the capability

I think NFTs are really more fundamental than both FTs and satoshi amount. They expose an interface to set permissions on UTXOs. Recall Group Tokenization's "authorities", but afaik Andrew never considered the permission to fan-out. I briefly considered [something similar](https://gitlab.com/0353F40E/group-tokenization/-/issues/25) but the NFT concept you brought in with CT2 eluded me.

Consider defining it as bit flags:

- `NFT_ONE = 0x01`, *(b00000001)* - allowed to create 1 or 0 children (implicit burn), can also be thought of as capability to exist.
- `NFT_MANY = 0x02`, *(b00000010)* - allowed to create many or 0 children (implicit burn).
- `NFT_EDIT_SCRIPT = 0x04`, *(b00000100)* - allowed to change "locking script" field of children
- `NFT_EDIT_COMMITMENT = 0x08`, *(b00001000)* - allowed to change "commitment" field of children
- `NFT_OPEN_FOR_SATS = 0x10`, *(b00010000)* - allowed to take sats in/out
- `NFT_OPEN_FOR_FUNGIBLE_TOKENS = 0x20`, *(b00100000)* - allowed to take fungible tokens in/out
- `NFT_CONFER 0x40`, *(b01000000)* - allowed to pass on capabilities that it has

It's hard to think of more possibilities, maybe a capability to demote capability, or capability to inherit capability from multiple parents instead of having to inherit it in full from at least 1 parent. Plus there are nits on defining how exactly would these OPEN_FOR capabilities work - where's the boundary of what's considered to be "inside" the fence? at categoryID or categoryID+commitment or categoryID+script or categoryID+commitment+script? How would NFT_CONFER work? The idea is to have one-time use capabilities but should it be applied to all or just some capabilities?

Currently, our UTXOs have all of those perms on by default with no interface to remove them. Your CT2.1 would have these "always on":

- `NFT_ONE | NFT_EDIT_SCRIPT | NFT_OPEN_FOR_SATS | NFT_OPEN_FOR_FUNGIBLE_TOKENS | NFT_CONFER`

exposing only `NFT_MANY` and `NFT_EDIT_COMMITMENT` but not all combinations would be allowed - can't have  NFT_MANY  without the NFT_EDIT_COMMITMENT.

It would map like this to CT2.1 capabilities:

- `IMMUTABLE = NFT_ONE | NFT_EDIT_SCRIPT | NFT_OPEN_FOR_SATS | NFT_OPEN_FOR_FUNGIBLE_TOKENS | NFT_CONFER`, *(b01110101)*, *(0x75)*
- `MUTABLE = NFT_ONE | NFT_EDIT_SCRIPT | NFT_EDIT_COMMITMENT | NFT_OPEN_FOR_SATS | NFT_OPEN_FOR_FUNGIBLE_TOKENS | NFT_CONFER`, *(b01111101)*, *(0x7D)*
- `MINT = NFT_ONE | NFT_MANY | NFT_EDIT_SCRIPT | NFT_EDIT_COMMITMENT | NFT_OPEN_FOR_SATS | NFT_OPEN_FOR_FUNGIBLE_TOKENS | NFT_CONFER`, *(b01111111)*, *(0x7F)*

aaaanyway... considering all possibilities adds complexity even to our discussions... I'm not sure how much energy you'd want to spend for the rationale on why NOT include some. I consider the NFT_EDIT_SCRIPT and the "cloneable" combo to be worth considering now or at least leaving in gaps for them, and it'd conveniently fit into half a byte so would let us use the other half for [other things (encoding optimization)](https://github.com/bitjson/cashtokens/issues/27#issuecomment-1178746721).

**Comment by A60AB5450353F40E** [comment]
closing this one, it was just exploring some additional capability definitions but let's stick to the 3 (immutable, mutable, mint) and move on...

**Comment by bitjson** [comment]
Thanks, I'll just leave this issue open until `cloneable` has a clear rationale section (and maybe some of the others too).

**Comment by A60AB5450353F40E** [comment]
To add to the above list, there's a possibility for NULL_CAPABILITY meaning "burned NFT" which we also don't really need because immutable+OP_RETURN is cheaper for Script API.

https://github.com/bitjson/cashtokens/issues/28#issuecomment-1181870869

**Comment by A60AB5450353F40E** [comment]
Also... the above is really overthinking it, it could be used for some rationale sections but for current spec we should go with 0-immutable 1-mutable 2-mint. There's a convenience too: if your category never created a `mint` then you can use OP_IF directly to distinguish immutable/mutable, even after proposed MalFix.

If we want to add a new version with cloneable later, it would be 3-cloneable. For others, higher bits could be interpreted as saying "deny X", where script immutability would then work like "deny changing script" and combinations would use values 4-7.

**Comment by bitjson** [comment]
> Also... the above is really overthinking it, it could be used for some rationale sections but for current spec we should go with [...] If we want to add a new version with cloneable later [...]

This spec should leave no stone unturned. (And I'm a bit confused with this comment because I thought [you concluded the same](https://github.com/bitjson/cashtokens/issues/31)?) 

We [get one shot to get tokens right](https://github.com/bitjson/cashtokens/issues/24#issuecomment-1179224180), upgrades will be hard or impossible. If you think `cloneable` might ever be a good idea, please prove it so we can include it.

**Comment by A60AB5450353F40E** [comment]
>This spec should leave no stone unturned. (And I'm a bit confused with this comment because I thought https://github.com/bitjson/cashtokens/issues/31?)

I think it is upgradeable-but-hard, with a new PFX that could switch the flavor of consensus rules - and it could share the encoding format so it wouldn't break parsers and add some of those potential capabilities which is why my attention is on the encoding format. Script API could just append the upgraded PFX in front of the ID when inspecting new categories so old categories would work under their own old rules, and upgraded tokens under upgraded rules - but they could share a lot of implementation groundwork CT2 is laying and maybe even the Script API - where the PFX would be prepended to the ID as a version byte.

>We https://github.com/bitjson/cashtokens/issues/24#issuecomment-1179224180, upgrades will be hard or impossible. If you think cloneable might ever be a good idea, please prove it so we can include it.

I'm happy with "not impossible". You designed a whole DEX, if you didn't feel like any of this was missing I doubt I could come up with something. Problem is - there's not many builders sketching out app designs using CT2. We need to attract them and CT2 ought to be enough, and then after a few years of building stuff and trying various approaches maybe someone will say "oh damn, we definitely want something that can do X better, let's make a CHIP!".

Trade-off for cloneable is this: it's adding some [more data](https://gitlab.com/0353F40E/group-tokenization/-/blob/6094119dd5c557b5b4132f415280448446e5aa96/CHIP-2021-02_Unforgeable_Categories-Native_Token_Primitives_for_Bitcoin_Cash.md#suggested-implementation) to those indexes we have to build anyway (one keyed by `category_id` and a sub-index keyed by `category_id+commitment`) - and the benefit would be easier delegation and sharing access when commitments are to be used for such purpose. To me it just seems like it could be useful even though I can't demonstrate a practical use for it, but we could get it for nearly free so why not throw it into the mix?

In that case we'd use the full 2-bits of space and have 0-immutable 1-mutable 2-cloneable 3-mint, feels more complete to me. Rationale to add cloneable is weak because I don't have a good example, but rationale to remove it is also weak because the cost is rather small. The cost is fixed but the benefits may grow if more people will use our system and find cloneable beneficial. Maybe that could make a rationale FOR cloneable?

Additional cost for "immutable-script" (could be clonable, muteable, or immutable, just like commitment) but this would be more expensive: it would need another validation sub-index for each `category_id`, keyed by `category_id+locking_script` so here it's not "free" anymore and should be weighted against some more concrete uses, which I can't come up with.

Additional cost for entangling NFTs with FTs or sats would be few more values under same indexes (add amount sums per `category_id+commitment` and `category_id+locking_script`) and here our encoding would start to get more complicated because we don't have enough bits so we'd have to spill over to 1 more byte, plus it would introduce new concepts for dealing with tokens.

**Comment by A60AB5450353F40E** [comment]
>the above is really overthinking it

One note re this... it was mainly a reference to overthinking the particular arrangement of bits to encode those theoretical future features. No reason to leave gaps for them, since whatever the bit we leave free - it can be interpreted as "allow X" or "deny X" to support the hypothetical upgrade. So... the simplest seems 0,1,2 or 0,1,2,3 if we can rationalize squeezing cloneable in.
