### ISSUE TITLE
Improve `Shared Codepoint for All Tokens` Rationale

### ISSUE THREAD

**Issue by bitjson** [bitjson/cashtokens#27]
The [`Shared Codepoint for All Tokens`](https://github.com/bitjson/cashtokens/tree/f8b500a051f82d42dbf9e9e890bc6cdc14592307#shared-codepoint-for-all-tokens) rationale was written for a pre-release iteration of the CHIP and has gotten progressively weaker. (Now that we're [reusing the token inspection operation codepoints](https://github.com/bitjson/cashtokens/issues/7#issuecomment-1065480447) to indicate a token prefix, additional encodings do not "cost" instruction set codepoints.)

 I'm starting to think that rather than the sort of compound encoding we're currently using (`PREFIX_TOKEN <category_id> <has_nft> [commitment_length commitment] <ft_amount>`), we should use multiple prefixes to avoid the `0x00` placeholders being used.

So we'd have encodings for each of:
1. Only fungible tokens – e.g. `PREFIX_FUNGIBLETOKENS <category_id> <ft_amount>`
2. Only a nonfungible token – e.g. `PREFIX_NONFUNGIBLETOKEN <category_id> <capability> <commitment_length> [commitment]`
3. Both – e.g. `PREFIX_TOKENS <category_id> <capability> <ft_amount> <commitment_length> [commitment]`

This saves 1 byte per output when encoding only fungible tokens or only a nonfungible token (likely far more common than instances where both types are held), and it makes the encodings themselves simpler: there's no "empty NFT" or "zero FTs" state, and the presence of FTs and NFTs can always be determined by only the prefix.

Previously I'd thought that a shared prefix would make adding support to indexers slightly simpler, but in reality, indexers will almost certainly "translate" token encodings for their database; the encoding of tokens in transactions should just focus on being as simple and efficient as possible.

**Comment by cculianu** [comment]
I agree that having multiple prefixes is not ideal.  It makes implementations more awkward and not ideal. 

Just use a single prefix byte to denote "token serialization hack is what follows", and then def. prefer encoding as much as possible in the capability byte that must follow anyway.

**Comment by A60AB5450353F40E** [comment]
Ok, same as above but shifted format bits so we can "eyeball" for FTs: odd higher half-byte means has FT, even means it doesn't.
I hope below tables make it all clearer, also added a column to show serialization length and what introspectio opcodes ought to return.

### Output format

`PREFIX_TOKENS <category_id> <token_output_format | nft_capability> [<commitment_length><commitment>] [ft_amount]`

Token Output Format is specified at higher half-byte.

`token_output_format` | bit7 | bit6 | bit5 | bit4 | bit3 | bit2 | bit1 | bit0 | Note
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0x10 (16) | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | FT
0x40 (64) | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | NFT
0x50 (80) | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | BOTH
0x60 (96) | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | NFT+commitment
0x70 (112) | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | BOTH+commitment

### NFT Capability

NFT Capability is specified at lower half-byte.

`nft_capability` | bit7 | bit6 | bit5 | bit4 | bit3 | bit2 | bit1 | bit0 | Note
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0x03 (3) | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | Immutable NFT
0x07 (7) | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 1 | Mutable NFT
0x0F (15) | 0 | 0 | 0 | 0 | 1 | 1 | 1 | 1 | Mint NFT

### Allowed Encodings

Allowed combinations are listed below

`token_output_format` \| `nft_capability` | bit7 | bit6 | bit5 | bit4 | bit3 | bit2 | bit1 | bit0 | Note | Serialization Length | `OP_*TOKENID` | `OP_*TOKENCOMMITMENT` | `OP_*TOKENAMOUNT` |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
0x10 (16) | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | FT | 34 to 42 | categoryID | EMPTY<sup>1</sup> | ft_amount<sup>2</sup>
0x43 (67) | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 1 | Immutable NFT | 33 | categoryID+0x03 | EMPTY<sup>1</sup> | EMPTY<sup>1</sup>
0x47 (71) | 0 | 1 | 0 | 0 | 0 | 1 | 1 | 1 | Mutable NFT | 33 | categoryID+0x07| EMPTY<sup>1</sup> | EMPTY<sup>1</sup>
0x4F (79) | 0 | 1 | 0 | 0 | 1 | 1 | 1 | 1 | Mint NFT | 33 | categoryID+0x0F | EMPTY<sup>1</sup> | EMPTY<sup>1</sup>
0x53 (83) | 0 | 1 | 0 | 1 | 0 | 0 | 1 | 1 | FT + Immutable NFT | 34 to 42 | categoryID+0x03 | EMPTY<sup>1</sup> | ft_amount<sup>2</sup>
0x57 (87) | 0 | 1 | 0 | 1 | 0 | 1 | 1 | 1 | FT + Mutable NFT | 34 to 42 | categoryID+0x07 | EMPTY<sup>1</sup> | ft_amount<sup>2</sup>
0x5F (95) | 0 | 1 | 0 | 1 | 1 | 1 | 1 | 1 | FT + Mint NFT | 34 to 42 | categoryID+0x0F | EMPTY<sup>1</sup> | ft_amount<sup>2</sup>
0x63 (99) | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 1 | Immutable NFT + commitment | 35 to 74 | categoryID+0x03 | commitment<sup>3</sup> | EMPTY<sup>1</sup>
0x67 (103) | 0 | 1 | 1 | 0 | 0 | 1 | 1 | 1 | Mutable NFT + commitment | 35 to 74 | categoryID+0x07 | commitment<sup>3</sup> | EMPTY<sup>1</sup>
0x6F (111) | 0 | 1 | 1 | 0 | 1 | 1 | 1 | 1 | Mint NFT + commitment | 35 to 74 | categoryID+0x0F | commitment<sup>3</sup> | EMPTY<sup>1</sup>
0x73 (115) | 0 | 1 | 1 | 1 | 0 | 0 | 1 | 1 | FT + Immutable NFT + commitment | 36 to 83 | categoryID+0x03 | commitment<sup>3</sup> | ft_amount<sup>2</sup>
0x77 (119) | 0 | 1 | 1 | 1 | 0 | 1 | 1 | 1 | FT + Mutable NFT + commitment | 36 to 83 | categoryID+0x07 | commitment<sup>3</sup> | ft_amount<sup>2</sup>
0x7F (127) | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | FT + Mint NFT + commitment | 36 to 83 | categoryID+0x0F | commitment<sup>3</sup> | ft_amount<sup>2</sup>

1. EMPTY indicates an empty stack item, which matches the result of OP_0.
2. Encoding "has FT" with ft_amount=0 is prohibited. Were it allowed, the opcode would also return EMPTY.
3. Encoding "has commitment" with commitment_length=0 is prohibited. Were it allowed, the opcode would also return EMPTY. Encoding "has commitment" with commitment_length=1 and commitment=0x00 must have the opcode return a 1-byte array with the byte equal to 0x00 and shall NOT return an empty stack item.

### Disabled Encodings

Notes on some disabled combinations, but which could be defined to have logical sense:

- Capability of 0x01 could mean: allow only 1 output but it must match BOTH the locking script and commitment of the parent
- Capability of 0x09 could mean: allow any number of outputs but they must all match BOTH the locking script and commitment of the parent
- Capability of 0x0B could mean: allow any mumber of outputs but they must all match the commitment of the parent
- Capability of 0x0D could mean: allow any mumber of outputs but they must all match the locking script of the parent

Enabling them later would require a new PFX to be specified in order to not break Script API, but it could at least share the encoding.

**Comment by bitjson** [comment]
@cculianu:

> I agree that having multiple prefixes is not ideal. It makes implementations more awkward and not ideal.
>
> Just use a single prefix byte to denote "token serialization hack is what follows", and then def. prefer encoding as much as possible in the capability byte that must follow anyway.

(or maybe @imaginaryusername given the 👍) Could you help describe your rationale here?

My hope with this issue is to either improve the currently-weak rationale ([`Shared Codepoint for All Tokens`](https://github.com/bitjson/cashtokens/tree/f8b500a051f82d42dbf9e9e890bc6cdc14592307#shared-codepoint-for-all-tokens)) or change the encoding given stronger rationale.

**Comment by bitjson** [comment]
@A60AB5450353F40E It looks like you copy/pasted several blocks of contents across several issues, making it a bit harder to follow the conversation. Would you mind editing those comments to simply link to the issue you opened with the full description? https://github.com/bitjson/cashtokens/issues/28 

> If you go with 3 prefixes then you need code-switching to read what follows and it eats into our "code points" space for no reason. 

Using a single prefix also requires code switching, and given the inspection operations added by the current version of the spec, we can use up to 6 prefixes at no additional cost. Are there other reasons that allow us to dismiss a 3-prefix encoding strategy?

> You can achieve the same with a single pfx and encoding 2 bit flags in the next byte - a byte you can't shave off and need to have anyway.

Does this not waste a byte when encoding only fungible tokens? (And if so, have you written rationale anywhere for why that is a worthwhile tradeoff?)

**Comment by bitjson** [comment]
> That case is the same as your 3-pfx aproach, becasue even with that you can't have 33b encoding of 0-amount FT

This doesn't seem to be correct – the above `PREFIX_FUNGIBLETOKENS` would support `33b encoding of 0-amount FT`, but that's also not a design goal; we would probably keep the current behavior of forbidding such "empty" fungible token encodings, contracts have other options for that behavior.

Are there other reasons that allow us to dismiss a 3-prefix encoding strategy?

**Comment by A60AB5450353F40E** [comment]
> > That case is the same as your 3-pfx aproach, becasue even with that you can't have 33b encoding of 0-amount FT
> 
> This doesn't seem to be correct – the above `PREFIX_FUNGIBLETOKENS` would support `33b encoding of 0-amount FT`, but that's also not a design goal; we would probably keep the current behavior of forbidding such "empty" fungible token encodings, contracts have other options for that behavior.
> 
> Are there other reasons that allow us to dismiss a 3-prefix encoding strategy?

Nmv I confused myself when I was looking at 0-amount edge case.

You have: `PREFIX_FUNGIBLETOKENS <category_id> <ft_amount>`, that's 33b (excluding the pfx)

#34 has: `PREFIX_TOKENS <category_id> <token_format | nft_capability> [ft_amount]` which would be 34b total for 0-amount and 35b for >0 amounts.

On the other hand, if you use only 3 pfxes, then how do you encode skipping the `commitment_amount` when it is 0?

You'd have: `PREFIX_NONFUNGIBLETOKEN <category_id> <capability> <commitment_length> [commitment]`, that's 34b (excluding the pfx)

#34 has: `PREFIX_TOKENS <category_id> <token_format | nft_capability> [<commitment_length><commitment>]` which would be 33b total for 0-commitment because both length and commitment would be skipped.

If you wanted to shave a byte there, you'd need either more prefixes or the `<token_format | nft_capability>` method.

If we used both approaches, we could do with 2 pfxes, one for FT-only, and one for NFT/BOTH, where the NFT/BOTH would squeeze 2 bits into the next byte (hasFT and hasCommitment bits).

**Comment by bitjson** [comment]
Responded here: https://github.com/bitjson/cashtokens/issues/28#issuecomment-1184671507

**Comment by bitjson** [comment]
I think the strongest argument here is probably that tokens aren't expected to be present on the majority of outputs, and inspecting each output for a single prefix is relatively less expensive than inspecting every output for 3 different prefixes.

Because we're splicing this encoding into to the existing transaction format, we should probably prioritize that performance/simplicity over the 1-byte of potential savings in the encoding itself. A future transaction format (e.g. v3) could make a different decision after seeing on-chain usage, but the `token outputs/total outputs` ratio would have to be fairly high to justify multiple checks for tokens.

**Comment by bitjson** [comment]
@imaginaryusername [offered another good rationale](https://github.com/bitjson/cashtokens/issues/28#issuecomment-1184697591) that separating the "deserialization marker" from capability makes implementations simpler. (And I agree that's the case in Libauth too.)

**Comment by A60AB5450353F40E** [comment]
Yeah I tried to integrate his and Calin's comments into this: https://github.com/bitjson/cashtokens/issues/28#issuecomment-1184716779
