### ISSUE TITLE
Rationale for `immutable` tokens not returning a capability byte from `OP_*TOKENCATEGORY`

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#29]
This is a follow-up to #25 .

Using native introspection, it's currently impossible to differentiate an NFT_Immutable with a 0-byte commitment and an NFT_Fungible.  Both return the exact same thing for`OP_OUTPUTTOKENCOMMITMENT` and `OP_OUTPUTTOKENCATEGORY` (and the UTXO counterpart opcodes).

Both return a categoryId *without* the `0x11` byte (or `0x0` byte) appended (as per latest spec).

There is no way for a contract to differentiate the two.  Suggest: making `NFT_Immutable` append the `0x11` byte anyway, to differentiate it from a FT.

**Comment by A60AB5450353F40E** [comment]
Oh yeah I haven't even noticed it's not consistent, should be: if the output has an NFT then append whatever is written in `nft_capability`.

**Comment by cculianu** [comment]
I agree.  Waiting for Jason's ok on this -- but i think the fact that it doesn't do that is a leftover wart from an older version of this spec..

**Comment by bitjson** [comment]
Shared some rationale for why differentiating those cases is not impossible, even if we drop the `0x00` behavior from `OP_*TOKENCOMMITMENT`: https://github.com/bitjson/cashtokens/issues/25#issuecomment-1182544507

As mentioned there, well-optimized contracts/compilers are unlikely to use any feature we add to make differentiating these cases easier.

On the other hand, if we append another byte for "NFT is present" to `OP_*TOKENCATEGORY`, we're starting to mix up its purpose in the API exposed to contracts. Suddenly contracts can no longer directly compare category+capability between two outputs (requiring `OP_SPLIT` and manual inspection of that final byte), so [contract/transaction sizes would be larger, and many contracts would become vulnerable to a new class of security issues caused by token API changes](https://github.com/bitjson/cashtokens#including-capabilities-in-token-category-inspection-operations).

**Comment by A60AB5450353F40E** [comment]
@bitjson it's not another byte, the capability byte (when ID+nft_capability is returned) doubles as "has nft" but current spec seems to entirely omit the capability byte for capability=0x11 and would return plain ID even if there's an immutable nft attached to the utxo.

**Comment by A60AB5450353F40E** [comment]
See table here https://github.com/bitjson/cashtokens/issues/25#issuecomment-1183505165 for possible combinations of Script VM state after executing all 3 introspection opcodes on an output

**Comment by cculianu** [comment]
Yeah I'm pretty sure @bitjson didn't understand the issue, @A60AB5450353F40E  :)

Still waiting on @bitjson to understand this and ok it.

**Comment by bitjson** [comment]
@cculianu: sorry, my wording was confusing, but I'm on the same page – the spec currently returns 33 bytes for `minting`/`mutable`, and 32 bytes for `immutable`/`none`. The proposal is to make `immutable` return 33 bytes as well (final byte being `0x11`).

The current behavior is very intentional and [requires some understanding of contract usage to grok](https://github.com/bitjson/cashtokens#including-capabilities-in-token-category-inspection-operations). I would really appreciate review of that rationale – if there's a better solution, I'd love to update the CHIP.

@A60AB5450353F40E and/or @cculianu: could you offer some more rationale for this change?

- What is the current behavior in various contract situations, and how does this change improve that behavior?
- How many bytes does it save, and when?
- Does it impact the security of the contract ecosystem?

(I'm trying to answer these questions myself now too.)

**Comment by cculianu** [comment]
I have trouble understanding wby you **wouldn't** return the capability byte there as the 33rd byte in situations where that byte is not 0.  It makes no sense to me that you would not append it.  

Seriously, I don't really understand why you wouldn't return it. `0x11 != 0x0`.

And you want to be able to differentiate between NFT and FT-only capability id's.  Right now the spec is ambiguous in places between the two.. it seems this API could be more regular if we returned it.


Now -- you wrote me some wall of text that I don't understand that is kind of dense and hard to read.

I await @A60AB5450353F40E to parse what you are saying and either agree with your or disagree since maybe he has more background in the subtleties of contract authorship.

**Comment by bitjson** [comment]
> Seriously, I don't really understand why you wouldn't return it. 0x11 != 0x0.

We wouldn't want to return it if doing so 1) offered no benefit in contract usage, and 2) forced a very common class of token-related contracts to waste 3 additional bytes on every category validation.

If we had some rationale for the importance of always being able to differentiate the cases in a single way, we may even prefer to disable zero-length commitments altogether rather than change the behavior of `OP_*TOKENCATEGORY`. (Though I think the rationale is currently strongest for [including them and not modifying the behavior of `OP_*TOKENCATEGORY`](https://github.com/bitjson/cashtokens/issues/25#issuecomment-1182544507).)

**Comment by cculianu** [comment]
Ok so we don't include 0x11?  You are ok with that? Honestly it seems to me like basic functionality but if you claim nobody would ever want that ever .. I have no idea.  I don't write contracts.  Seems strange.  APIs normally don't work this way but ok.

**Comment by A60AB5450353F40E** [comment]
Ok I think I get the rationale for omitting it, although there will still be some ambiguity when it comes to Script API:

- If OP\*ID returns plain 32b `category_id`, OP\*COMMITMENT returns `{}`, and OP\*AMOUNT returns `{}` then that would clearly mean immutable NFT.
- If OP\*ID returns plain 32b `category_id`, OP\*COMMITMENT returns `{}`, and OP\*AMOUNT returns `ft_amount` then that VM state has ambiguity: is it a result of a pure FT or is it a result of FT+immutable NFT?

If we want to return pure `ID` for immutable then lets specify the encoding to match, so immutable NFT encoding should be encoded using a 0. I have updated proposed format (#28) to reflect this, and we'd avoid this confusing "cross-wiring" where 0x11 in encoding would map to 0x00 in Script API.

**Comment by cculianu** [comment]
I mean I still don't get why you would want to omit potentially useful data --  but if script authors would find that omitted data the opposite of useful, I'll take your word for it.  Still makes no sense to me.

Ok so nothing changes.. got it.

**Comment by bitjson** [comment]
Rationale done in https://github.com/bitjson/cashtokens/pull/58 🚀
