### ISSUE TITLE
Two-stage activation (minimize long-term impact of activation)

### ISSUE THREAD

**Issue by bitjson** [bitjson/cashtokens#36]
@zander brought up that a two-stage activation might allow us to clean up any "pre-activation token-forgery outputs" before tokens are activated, e.g.:

At block `N`, outputs beginning with `PREFIX_TOKEN` become effectively `OP_TRUE`, while new token encodings are validated properly (but minting tokens is still useless, as the output can be spent by anyone). At block `N+X`, spending validation activates.

Opening an issue to explore if this strategy would allow us to simplify the upgrade logic that will ultimately remain in node implementations.

**Comment by imaginaryusername** [comment]
I'm not seeing the supposed benefit to simplicity by having two activation times instead of one, where nodes now have to implement one more intermediate and strictly useless ruleset.

**Comment by A60AB5450353F40E** [comment]
and it would linger on forever as an exception for blocks between N and N+X, whereas with simpler MTP activation, the code that was used to check the height could later be cleaned up.

**Comment by zander** [comment]
yeah, the description from Jason lost a lot in copying it from telegram here.

so, the point here is this;

at activation time (call it block N) you allow anyone to spent any outputs that have been created which actually uses the codepoint unique to cashtokens. It basically becomes an 'anyone can spent'. This allows people to sweep the funds for themselves and cleanup.
At the same time you ensure that no new transactions can be mined which violate the rules.

Maybe a 100 block later you actually activate the proposal.

What this means is that at the second activation period you are 100% sure that no outputs exist in the UTXO which use the codepoints of the cashtoken.

This solves a pretty big activation problem. We made known the opcode for this proposal and people can populate the utxo with such outputs prior to the activation. Those will not have been validated and can say anything. So, activation is an issue and the code would likely have to have a check to see if an output was from before the activation time before it is used.

To completely empty the UTXO of such bogus outputs is thus a big deal as you avoid needing to make the full node check (forever!) if any output is from before the activation point.

Additionally, you remove any incentive anyone may have of creating such outputs in the first place.

**Comment by zander** [comment]
@A60AB5450353F40E that cleanup of rules can happen anyway. The "N" is naturally simply MTP based and can later be replaced with a block-height like always. In this case it would simply be changed to say "N+100" (or whatever Jasons X we choose).

**Comment by A60AB5450353F40E** [comment]
Ahh right... the blockchain can later be processed as if those outputs were "anyone can spend" from block 0.

Ok so current situation: they are "nobody can spend", then at some MTP triggered at N they become "anyone can spend, but can not create new ones", and then there's a cleanup period, and then at some MTP triggered at N+X it becomes "anyone can create and spend if the transaction satisfies CT2.X spec", and later the code to validate blocks 0 to N+X-1 can be cleaned up to "anyone can spend".

AFAIK the current idea is: purge all historical outputs from UTXO db and don't add any new ones until MTP activates CT2.X spec. Man I wish we had already locked TX version

**Comment by imaginaryusername** [comment]
Okay, I get it: the point is within the 100 block period (maybe literally on block 100), violators of upcoming new rules will be removed, paving the way for the new rules to start "clean". There are two problems with this line of thought:

1. It still incurs two rulesets that have to be maintained indefinitely. It's not clear whether this is more burden for implementations than banning previous outputs at one activation.

2. Basing a rigid activation on transactions is risky: The strategy can be spammed, DoS'd, soft-blocked by adversarial miner - many problematic scenarios that can be inflicted with relatively little cost. Many mitigations exist, but they all add even more to complexity, and makes one question why don't we just do one activation in the first place, bite the bullet and ban possible old UTXOs.

**Comment by zander** [comment]
@imaginaryusername 

your point one is addressed in the comment to bca, there would not be 2 rulesets after this.

your second point raises questions. You say the strategy can be spammed. What does that mean? As far as I can tell all this does is use a more natural way to spent outputs. Can you explain your point?

The suggestion to black-list and ban old UTXOs is an interesting one. You do realize that this would creat a new ruleset which has to be kept forever, right?

**Comment by A60AB5450353F40E** [comment]
>Basing a rigid activation on transactions is risky

What he's talking about could be done with MTP too... at MTP X you enable freely spending all UTXOs starting with our PFX and prohibit creation of new ones. At MTP X+T you start enforcing CT2.X rules. In the window between those 2 points in time, any miner would be free to cleaned up (donate to himself) UTXOs starting with the PFX made before MTP X.

**Comment by imaginaryusername** [comment]
The strategy can be spammed or otherwise DoS'd, because its soundness depends on having specific "cleanup" transactions (of unknown quantity!) be included within a limited timeframe. One can easily imagine scenarios where

- an adversary litters the UTXO with outputs to be cleaned up pre-activation, making it difficult to get all of them in a timely and cheap manner. 

- an adversary starts mining and censors cleanup transactions. It'll be difficult to prevent _all_ cleanups from going through, but they can compound the above problem without incurring much additional cost. 

- the adversary can spam while mining (before you start prohibiting creation) to give himself low fees and/or low utxo sat requirements, further compounding the above.

- (add other ways to either multiply impact of UTXOs needing cleanup or otherwise complicate efforts to include cleanup) 

In other words, it's difficult to ensure the success of a "cleanup" operation that depends on cleanup transactions being included in a timely manner. If even one slips through without getting cleaned up, the strategy failed!

@A60AB5450353F40E these points apply for both MTP and block number variants

re: two rulesets, I understand that the anyonecanspend can be retroactively applied to all outputs since block 0, but that'll still be two _new_ rulesets. We can't get rid of the anyonecanspend rule, we can only replace the previous (undefined, no maintenance burden) rule with it. 

Re: blacklist and ban, you don't actually have a specific "blacklist", whether a UTXO is spendable is simply decided based on their age in term of block, the specific number of which can be determined at activation (and later hardcoded), and is already available as context for transaction evaluation anyway.

**Comment by zander** [comment]
You bring up some really interesting game theory points.

A hashwar to get rid of non-standard transactions! Who wins?

The reality of such games are always about balance and we are here to design something that balances it in your favour. As such your input is invaluable to understand the "X" (amount of blocks) to allow any cleanup to happen. How much of our hashpower is going to support the normal operation and mine normal transactions? Will we see a chain-split over this?

None of these are really hard to solve and a balance is not that hard to find. We don't even have to pick one solution over anohter, both is fine since if one works the other is irrelevant and can be sunset later.

What is relevant here is the game-theory part where this strategy (as OP describes) changes the balance of the game very much in our favour.

The cost of getting a transaction mined before time which upsets cashtokens is non-zero. The cost of getting rid of them is negative (you get paid to do).

As such I would not discount this option. It is so far the only option that actually has the opportunity to pass the activation point (+X blocks) with exactly 1 ruleset.

**Comment by zander** [comment]
> If their existence can be simply ignored by new rules

Not having those extra rules is better.

**Comment by bitjson** [comment]
Hi all, I think this has been resolved in recent months, but wanted to check in before closing this issue:

Are there any further issues with the activation strategy after https://github.com/bitjson/cashtokens/pull/62? 

This now describes how it's implemented in the BCHN patch, and I think it minimize the long-term impact after activation as much as possible. (Of course, if anyone knows of a way to reduce the impact further, please share!)
