### ISSUE TITLE
sighash question

### ISSUE THREAD

**Issue by zander** [bitjson/cashtokens#38]
The spec states;

> The SIGHASH_UTXOS and SIGHASH_ANYONECANPAY types must not be used together; if a signature in which both flags are enabled is encountered during VM evaluation, an error is emitted (evaluation fails).

First of all, this should likely not be validatd in the VM, but before. But the real reason I'm opening this issue is because I don't think this should be a consensus rule. It feels very much like a standardness rule. Falls much more in line with the kind of checks that happen there anyway.

**Comment by A60AB5450353F40E** [comment]
Having them both would result in a duplicate data being added to the preimage. Satoshi amount and modified locking script are already included by current definition even with `SIGHASH_NONE | SIGHASH_ANYONECANPAY`, and CT specification also adds the signing input's prevout token payload to the preimage even without SIGHASH_UTXOS - and this is intentional in order to prevent accidental burns by non-upgraded wallets

 `SIGHASH_UTXOS` would add nothing new when used with `SIGHASH_ANYONECANPAY` - it'd just add the prevout's data one more time - with some nuance in that it would be added as serialized. It would reveal some new data, though, because our modified_locking_script removes some info when inputs spending P2SH prevouts are doing the signing. Maybe we can improve on this somehow.

>this should likely not be validatd in the VM, but before

Signatures are entirely a VM feature. It is execution of `OP*SIG*` that reads whatever signature is on the stack, snips off the byte to know what kind of preimage to construct and then verifies the hash against the signature and key. The sighash byte needs not come directly from the input, the `locking script` could be deciding what type of signature is needed based on some `OP_IF` and appending it to the stack item. The spender would have to simulate Script execution to producing the signature for the required preimage format.

**Comment by zander** [comment]
I understand the point you are making and while it is naturally possible for someone to shoot themselves in the foot, the actual goal of avoiding said shooting is in Bitcoin solved in isStandard().

It would be a very cheap thing to test as extension of the current standardness checks.

Nothing breaks if people violate this rule so why make it a new consensus rule when a standardness rule suffices?

**Comment by A60AB5450353F40E** [comment]
>SIGHASH_UTXOS would add nothing new when used with SIGHASH_ANYONECANPAY - it'd just add the prevout's data one more time - with some nuance in that it would be added as serialized. It would reveal some new data, though, because our modified_locking_script removes some info when inputs spending P2SH prevouts are doing the signing. Maybe we can improve on this somehow.

@bitjson can't we just allow this too? It's not exactly the same, without SIGHASH_UTXOS if there are code separators in the redeem script then part of the prevout would be left out whereas with SIGHASH_UTXOS it would be included, too.

**Comment by imaginaryusername** [comment]
To repeat what I've emphasized elsewhere, we should not add new differences between consensus and standardness rules in general. It is a legacy device from a time when hardforks were very difficult as an upgrade mechanism, and has no place in BCH's de facto paradigm since 2017. Future upgrades should aim to remove such differences where possible instead of adding to them. 

As for `SIGHASH_UTXOS` + `ANYONECANPAY`: If there's no obvious use for it, disallowing the combination is a generally safer option for complexity and security. The proposal is already a sprawling behemoth and it's unwise to open another section exploring the implications of new combinations.

**Comment by zander** [comment]
>  we should not add new differences between consensus and standardness rules

Can you rewrite this sentence in a way that it becomes more clear? I don't know how to parse the word "differerences" in this sentence and don't actually understad what it is you are trying to say.

>  If there's no obvious use for it, disallowing the combination is a generally safer option for complexity and security.

Yes, that is agreed. Nobody proposed otherwise.

> The proposal is already a sprawling behemoth and it's unwise to open another section exploring the implications of new combinations.

That is exactly the point, nobody explored the implications (we just have the idea that they might not be useful) and putting any limiting rule in consensus before such an exploration has been made is unwise. Consensus is much harder to revert than a standardess rule, for instance.

But more to the point, similar to us having two transaction max-sizes (1MB and 100KB), the goal is different between those two limits. The first is allowed for people that know what they are doing (and if they don't, they only hurt themselves with it). The second is for the rest.

That is the point of a standardness rule. To soft-limit it for the 99% of the audience. But not completely cut off experimentation or useful usecases. We all agree on that, no?

**Comment by zander** [comment]
> @bitjson can't we just allow this too?

To be fair, I don't really see the downside of allowing the combination, would be nice if bitjason could explain why this is an issue. The earlier answer here was that the issue is:

> Having them both would result in a duplicate data being added to the preimage. 

But this doesn't seem to me to be an issue, why would that be a problem?
