### ISSUE TITLE
Reserved Supply

### ISSUE THREAD

**Issue by zander** [bitjson/cashtokens#39]
The spec today says this: ([Reserved Supply](https://github.com/bitjson/cashtokens#reserved-supply))

> A token category's reserved supply is the sum – at a particular moment in time – of tokens held in reserve by the issuing entity. This is the portion of the supply which the issuer represents as "not in circulation".

> The reserved supply of a fungible token category can be computed by retrieving all UTXOs which contain token prefixes matching the category ID, removing provably-destroyed outputs (spent to OP_RETURN outputs), and summing the amounts held in prefixes which have either the minting or mutable capability.

This raises several questions;

1. as the decision of what part of the supply constitutes 'reserved' is squarely put on the plate of the issuer, how is it possible to make an algorithm for this? That algo is at best a heuristic, and doesn't feel like it belongs in a spec.
2. We talk about provably destroyed outputs using op_returns. An op-return output is defined as **starting** with op_return. Yet cashtokens do the same, right? Doesn't that mean that they are mutualy incompatible?  
  Notice that for cashtokens you don't need op_returns to burn as the difference between input and output just goes poof anyway.
3.  what is a mutuble **fungible** token? In this context we are talking about a fungible token, we should count this by checking outputs that have the minting *or mutable* capability. Why would a fungible token ever have a mutable capability flag set?

**Comment by A60AB5450353F40E** [comment]
>what is a mutuble fungible token?

No such thing. There's only a "amount of fungible tokens that happens to live on the same utxo as some mutable-nft". The spender can freely split them up - unless the locking script requires that spending input proves that the spender isn't doing that (using introspection to check all outputs)

>An op-return output is defined as starting with op_return. Yet cashtokens do the same, right? Doesn't that mean that they are mutualy incompatible?

Cashtokens are serialized together with script to avoid breaking TX format, but they aren't part of the Script, so even a CT output can start with OP_RETURN and be explicitly burned like that. From the point of view of Script VM layer, it won't see the token prefix - it will see the Script as starting with OP_RETURN. Tokens can be implicitly burned by being ommited from the output side of a transaction, or explicitly by OP_RETURN - which is useful for contracts requiring a proof of burn (use OP_OUTPUTTOKENAMOUNT to check the FT amount and OP_OUTPUTBYTECODE to verify that it's burned) - this avoids having to use Script to tally the sum of outputs.

>how is it possible to make an algorithm for this? That algo is at best a heuristic, and doesn't feel like it belongs in a spec.

That section is more of informative nature, to demonstrate how token standards could be be set up using the primitives made available with the upgrade. Standard compliance verification can be delegated to another contract. Like, if you want your token to be automatically added to some token standard/collection - then you will need to reference a public covenant UTXO which will execute some code that verifies compliance with the standard. Failure to have and spend the "standard-vetter" UTXO in the genesis TX would mean your token is non-compliant with the standard and it would be ignored and reported as "unknown" by some wallet that would implement the standard.

The reserved supply could, for example, be locked into a covenant and be programmatically released, this is where allowing NFTs and FTs to live on the same output shines. If genesis TX creates exactly 1 immutable NFT and the whole FT supply is locked with a covenant on the NFT, then Script has much less job to do: it only needs to inspect 1 input and 1 output, because the "only 1 output" property will be guaranteed by consensus rules already so it only needs to subtract the output NFT's ft amount from the input NFTs prevout amount to know how many FTs are trying to "escape" from the NFT output.
