### ISSUE TITLE
Please describe more Terms 

### ISSUE THREAD

**Issue by zander** [bitjson/cashtokens#40]
The document starts with a listing of all technical terms used in the document. It currently limits itself to terms unique to cashtokens and I think that it would be useful to expand that to terms that are not so well known but required to understand cashtokens.

Specifically I would like to see a description of:

* Covenants
* Commitment

I learned about covenants from a high level overview quite some time ago and while they are not really mentioned in the spec, I believe they are crucial because they really are the glue that holds the different ingredients together.

I honestly still am fuzzy on commitments. The examples didn't really explain, instead they just used. So I guess they assume you already know how cashfusion is using commitments.

A little 2 paragraph **technicall** (can't stress this enough, this should no be fuzzy) description of each would be really a nice addition.

**Comment by A60AB5450353F40E** [comment]
Here's an attempt:

First let's get on the same page when we talk about locking bytecode and unlocking bytecode. Locking bytecode can be thought of as spending constraint function definition, and unlocking bytecode as function arguments, provided by the spender. Introspection CHIP introduced a more elegant way (less elegant way being the OP_CHECKDATASIG) to pass function arguments by reference (indexes of other inputs/outputs) in addition to the by value way (input data pushes). The spender can't lie about parts of the TX - the pattern with new opcodes is to provide just an index of some input or output - and the locking script fetches the data in a trusted way so the spender can't lie about the TX data. If the function evaluates to true - the input unlocks the prevout and the spender can do what he wants with the amount - usually create new output(s) sent to his address (note: p2pkh is also a function definition, with a hard-coded constant - the public key hash).

**Covenants**

Until OP_CHECKDATASIG, creator of the UTXO had no control over what the spender will do when he unlocks it. Introspection made that control more obvious and easy to understand: the function is now aware of its surroundings, and can for example require that the spender pays some % into some other address, and is free to do what he likes with the remainder. This is a covenant: a contract that enforces some constraint on how exactly the unlocked amount may be spent. It restricts the output side of transaction. [Here's an example](https://old.reddit.com/r/btc/comments/uqamxa/happy_bitcoin_cash_may2022_upgrade_follow_up_on/) made to celebrate May 2022 CHIP activation :)

**Commitment**

I have an [issue with this term](https://github.com/bitjson/cashtokens/issues/8), I would prefer "nft message" because that's what it is. It's a string-type field attached to the NFT. If the NFT is immutable - the NFT must carry its message unchanged. If it is mutable - it may be changed but still the cardinality is preserved, only 1 message-carrier output can be created on the output side for every mutable NFT spent on the input end. If a mint NFT is spent - it can emit multiple new messages, locked (immutable) or unlocked (mutable).

**Comment by zander** [comment]
thanks!

In your introduction you named the output-script a 'function', which makes a lot of sense.
In your description of a covenant you called it a "contract", but isn't it better to call it a function and stay consistent?

The commitment unfortunately stays a bit less clear. Ok, it is a message. I don't see the case made for WHY its a contractual commitment. Probably because nobody connected the commitment (or message) to any contracts/functions.

Why can't you just have the 'commitment' data hardcoded in the covenant?

**Comment by zander** [comment]
> Why can't you just have the 'commitment' data hardcoded in the covenant?

To be clear, that wasn't a suggestion :rofl: I know the generic concept behind it, just thought that it may be useful to explain why it is better than the silly option.

Thanks for reading.

**Comment by A60AB5450353F40E** [comment]
> isn't it better to call it a function and stay consistent?

"Function" gives us a nice mental model to explain what "contracts" placed on UTXOs really are, however "contract" is already deeply rooted in broader ecosystem as the term. UTXOs are really smart, programmable, units of cash. A "contract" is then a program defined by the locking script function.

>I don't see the case made for WHY its a contractual commitment.

When you create an immutable NFT you "commit" to carrying it forward unmodified, and consensus makes sure you respect your commitment so Script covenant is free of having to inspect every output to verify you didn't slip in another NFT of the category. Mutable allows freedom to modify the commitment but the program set on the input's prevout may require that it's updated only in some specific way, and when it has done its job, the contract can require the spender to demote the mutable to immutable, and he'd heep the NFT as proof that some contract clause was satisfied with a past TX - and the recipient could be assured that it really was even without looking up the TX which the NFT claims to have witnessed. This way, NFTs can be used as certified attestations of some past event, of a TX already pruned - and preserve the proof of it happening in the NFTs UTXO.

>Why can't you just have the 'commitment' data hardcoded in the covenant?

You could, and then the covenant (the script running on the input) would have to do verifying that exact same (or mutated, in case you need to change the key or some other part of the contract) locking script bytecode is passed on to 1 or 0 outputs of the same category, and to do that you'd have to: limit the total number of outputs in the TX to manageable quantity, and then use a series of `OP_IF` to verify that no more than 1 output of the category is being created.
