### ISSUE TITLE
Clarification: "invalid token prefixes" can just be locking bytecode

### ISSUE THREAD

**Issue by bitjson** [bitjson/cashtokens#41]
@thesquaregroot identified an ambiguity in the spec we need to be sure is handled explicitly: any locking bytecode can begin with `0xd0` (`OP_UTXOTOKENAMOUNT`), even for outputs that do not themselves contain tokens. There are many useful covenants that might begin with `OP_UTXOTOKENAMOUNT`, and those outputs may or may not also carry tokens. 

I overlooked this in the current version of the CHIP. I'll clarify the spec to ensure starting with `0xd0` isn't assumed to make the output invalid, and I've added this to the set of test vectors that will be in the next release. 👍

**Comment by A60AB5450353F40E** [comment]
During parsing the format non-compliance should not fail the TX but instead just skip interpreting the output as token, and the "malformed" token PFX would then be handed over to Script VM instead of being snipped off, and then it may or may not fail when executed as locking bytecode - it would depend on what such Script does. The PFX is much similar to P2SH. Outputs starting with P2SH pattern but having extra opcodes are still vallid but will be processed differently than P2SH "magic" pattern - simply executed as "bare" script. With tokens, we add one more such "magic" pattern.

**Comment by cculianu** [comment]
Yep, this is what I implemented already, since this ambiguity became obvious to me while implementing.  Yes, as I currently have it I do what you expect: if it parses ok according to the rules we described, it is loaded as token data and the remaining bytes are assigned to the locking bytecode.

if it doesn't parse ok, ALL the bytes are just treated as locking bytecode.

Note that under no circumstances using current consensus is it possible to spend any locking bytecode that starts with 0xd0 .. and in the future after activation if it started with 0xd0 but failed to parse.. it would not be possible to spend it either.

I would suggest that we forbid ANY locking bytecode from even being *created* after activation.. if it failed to parse as token data but started with `0xd0`.  The reason for this: to keep things as simple as  possible implementors....

**Comment by thesquaregroot** [comment]
> .. and in the future after activation if it started with 0xd0 but failed to parse.. it would not be possible to spend it either.

That's what I thought at first, too, since `0xd0` is currently a disabled opcode, but as Jason mentioned, `0xd0` is actually defined as a part of this CHIP to be `OP_UTXOTOKENAMOUNT`.  It would make it a non-standard output/transaction, but I believe it would be spendable if a miner were to include it in a block.  It's certainly an interesting use-case - a non-token output that depends on the data from token outputs - but I could see there being some interesting use-cases for it.

**Comment by cculianu** [comment]
Oh duh I'm stupid.  You're right -- if the scriptSig contains a push for the index parameter to the opcode.. there you go. It is spendable. Hmm... apologies for my mistake.

**Comment by cculianu** [comment]
Note I implemented this already and it became very clear to me that **we need to be clear on what is a parse error and what is not** in the spec.  As such, see some of my suggestions in #43.

**Comment by cculianu** [comment]
Stated again: If you **really** want this feature it opens up a pandora's box about what is parseable and what is not so the spec must be **very clear** on what to reject as a parse failure and what to not reject as a token data parse failure.  This is because bytes that are rejected as a token data parse failure now would be prepending to the locking script and thus have completely different rules applied to them (just script VM rules).  Whereas bytes that parse correctly are not subject to VM interpreter rules but are subject to token data validation consensus rules.

This consideration also applies to the **PATFOs** (pre-activation token forgery outputs) as well.  So **we must be very clear here**.

I feel that the way the spec is presently worded, even after my #43 suggestion above is not sufficiently explicit and clear about these things..... since getting it wrong could mean consensus faulure!

**Comment by cculianu** [comment]
See #44

**Comment by cculianu** [comment]
Hmm the more I think about this the more I think it’s not a great idea for prefix byte to do double duty like this. 

aside from the issues above…  there is the possibility that some locking script that is not trying to do anything funny but that starts with 0xd0 ends up “accidentally” looking like token data and failing to be spendable (corner case, I know). This last point bugs me as well, tbh.

 I think that either :

- we make a unique codepoint to denote token prefix (preferable)
- Or, we disallow locking scripts that don't parse correctly as token data (in effect forbidding 0xd0 as first opcode in non token scripts)


Tl;dr: not a fan of the ambiguity proposed here. It’s asking for trouble …

**Comment by A60AB5450353F40E** [comment]
Yeah, sharing the codepoint with introspection opcode seemed clever but it may be more trouble than it's worth.
As you say, we could just spec the PFX to be some codepoint that's NOT used as a valid opcode so there can be no double-duty.

**Comment by cculianu** [comment]
Yes..  thanks.

Note we could have two prefix bytes. 0x?? Which denotes “encapsulated payload” and a second byte for payload veraion, in this case maybe 0x0 or 0x1

This way we waste a code point .. but we gain the ability to embed extra metadata going forward into a txn.

And we also gain the ability to someday extend the token data serialization format by adding a new version byte that directs the serializer to the correct code paths appropriately.

(Before anybody panics that TWO bytes for prefix is a waste of space — I personally strongly believe that being stingy with 1 byte here or there at the expense of extensibility is perhaps misguided optimization… 1 extra byte per token out is not a huge deal, imho… if it buys us extensibility.)

**Comment by A60AB5450353F40E** [comment]
That would be a generalized TX format extension scheme but we don't have to do it now. It's the same with opcodes: if we run out of codepoints we'd have to use the last one to introduce 2-byte opcodes. For now, we still have headroom, and there weren't that many ideas for new fields, so I'd raise the "scope creep" flag here and repeat the Introspection CHIP [rationale](https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md#use-of-single-byte-opcodes) for single-byte opcodes:

>### Use of Single-Byte Opcodes

>Earlier proposals attempted to use fewer opcodes by either [introducing all introspection operations as a single opcode](https://github.com/bitjson/op-pushstate) or by [introducing multi-byte opcodes](https://github.com/bitjson/op-pushstate/pull/1). However, [deeper analysis](https://bitcoincashresearch.org/t/bitcoin-script-multi-byte-opcodes/347/5) indicates that the BCH instruction set [might never reach 255 operations](https://bitcoincashresearch.org/t/bitcoin-script-multi-byte-opcodes/347/9) within the current VM model (future VM models are likely to have their own independent set of operations, rather than naively extending the current instruction set).

>While it is likely wise to reserve both the remaining `OP_NOP4`-`OP_NOP10` range and the range from `0xf0` to `0xff` for future multi-byte opcodes (leaving room for ~6000 2-byte opcodes), jumping to multi-byte opcodes would be a premature optimization, with uncertain future benefit and immediate negative consequences.

>As such – and because introspection operations are critical to all covenant use cases – this proposal specifies the proposed operations as standard, single-byte opcodes.

**Comment by A60AB5450353F40E** [comment]
But if we use the 2nd byte as a version field specific to tokens, there is a benefit, we could upgrade tokens while maintaining API compatibility, but then we'd have to append the version byte to OP\*CATEGORY return value.

**Comment by cculianu** [comment]
Well whatever you guys think. I'm ok with no version byte.  If we need to extend the format we can always redefine the capability byte where some of its bits (if set) indicate an alternate extended format... so we do have headroom there.

Up to you guys.  

Irrespective of what you want to do about a version byte -- for now I'm going to go ahead and open an issue for my suggestion that the TOKEN_PREFIX be a unique codepoint that is otherwise an invalid opcode... Will do so now.

**Comment by imaginaryusername** [comment]
Using two bytes instead of one for a unique codepoint sounds entirely reasonable to me.

**Comment by cculianu** [comment]
> But if we use the 2nd byte as a version field specific to tokens, there is a benefit, we could upgrade tokens while maintaining API compatibility, but then we'd have to append the version byte to OP*CATEGORY return value.

Hmm.. would we? It really depends on whether we want to "Expose" how this token was serialized or not.  Caller may not care **how** the token ended up serialized... If it did then yes, we would need to append this byte. If it did not, then we would not.

I can imagine a reality where you extend tokens such that the new **richer tokens** that have an extended serialization format involve a set of properties and attributes that are a strict superset of the base "CashTokens v2" specified herein. In which case the new properties we introduce can just get "default values" if serialized with version `0x0` (which is what I am arbitrarily calling the currently specified "CashTokens v2").   Know what I mean?

**Comment by cculianu** [comment]
Hmm, regarding whether or not to use a version byte. We *could* not use a version byte but instead do this: https://github.com/bitjson/cashtokens/issues/48

**Comment by A60AB5450353F40E** [comment]
>Hmm.. would we? It really depends on whether we want to "Expose" how this token was serialized or not. Caller may not care how the token ended up serialized... If it did then yes, we would need to append this byte. If it did not, then we would not.

He may not, but the version would indicate more than serialization - it could indicate token consensus ruleset, like enable some new capability flag. How would the Script API know whether some NFT is constrained with v2 or v3 ruleset?

>Also if we do end up not being able to do the reality I am outlining above -- it's not a big deal to have "newer" tokens just append the version byte if it's not 0.... maybe?

Oh yeah, I think we could omit it for this "v0". Future versions would have to add it in order to break `OP*CATEGORY`.

Or... we could just have the PFX double-duty as version, and a future version would use up another codepoint but could share the Script API: https://github.com/bitjson/cashtokens/issues/31

**Comment by imaginaryusername** [comment]
While removing the ambiguity is very reasonable, it sounds like the exact way to do that (likely via #47, maybe with #48 on top, whether one-byte or two-bytes) make little immediate difference for Cashtokens itself. For the sake of expediency I'll recommend that @bitjson simply make a call among these choices and we stick to it.

**Comment by cculianu** [comment]
@imaginaryusername : Well #47 and #48 are not two different choices.  Definitely #47 needs to happen.  #48 is just optional and arguably not as critical... it's just me being paranoid about future-proofing but as @A60AB5450353F40E points out .. if we find we *really* need to upgrade the tokens we can always just use up another codepoint and that's that.  If we run out of code points we could make up an `OP_EXT` op-code that is a 2-byte opcode prefix, etc...

**Comment by cculianu** [comment]
@A60AB5450353F40E 

> Or... we could just have the PFX double-duty as version, and a future version would use up another codepoint but could share the Script API: https://github.com/bitjson/cashtokens/issues/31

That works actually.  I am 100% ok with that and with closing #48 .  We can just use a new codepoint in the future if we needed a new token format.. 100% ok by me.

**Comment by bitjson** [comment]
Hey y'all, catching up here, thanks for digging into this issue! And thanks @cculianu for noticing that this would make it possible for contracts to accidentally create token prefixes. That would become a practical vulnerability for some real contracts if output standardness is relaxed, and it's already a possibly-very-confusing behavior for nonstandard outputs. 

So I agree we should avoid the possibility and just use a single-purpose codepoint. I'm thinking the solution here is just to revert back to using `0xef` as `PREFIX_TOKEN`. (That lets any future prefixes start counting down from `0xef` while leaving the `0xf` range open for a multi-byte expansion if single-byte codepoints are ever exhausted.) Does that seem reasonable?

I'm still working on an implementation and larger set of test vectors in [libauth](https://github.com/bitauth/libauth), so I'll switch the codepoint and try to get everything merged in the next few days. 👍

**Comment by bitjson** [comment]
@cculianu summarized the resolution in https://github.com/bitjson/cashtokens/issues/47, so I'll merge this issue into that one.

**Comment by cculianu** [comment]
>  Does that seem reasonable?

@bitjson Hmm. As far as BCHN tests go, `0xef` is kind of awkward because we have this concept of `FIRST_UNDEFINED_OPCODE` value (which is presently `0xd6`).  Having another reserved codepoint beyond that at `0xef` makes the tests super weird and would cause me to have to rewrite a bunch of ancient code in `script_tests`.  I'd rather not do that since it's just busy work.  Please let's just go with `0xbf` to save me tons of development time and poor BCHN project needless cost in development hours paid out to me for my time.  

Also.. I already implemented it in my MR as `0xbf`.
