### ISSUE TITLE
Consider moving the "capability" byte to be the first thing we read right after TOKEN_PREFIX

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#48]
I suggest this in conjunction with #47 .

This idea came up as part of discussion in #41 here: https://github.com/bitjson/cashtokens/issues/41#issuecomment-1193352610

Note that if we move the capability byte to come *right after* the `TOKEN_PREFIX`, as the first thing we read (rather than category-id being the first thing we read, as specified currently), then this buys us a great deal of headroom and freedom to be able to completely extend or redo the token data serialization format in the future.  Since the capability byte has free bits in it, we could potentially use some of those bits (if set) to indicate a completely different serialization code path for some hypothetical future extended token serialization format.

**Comment by A60AB5450353F40E** [comment]
so we'd be packing 3 fields into 1 byte: `version | token_format | nft_capability` ? I'm not liking this, if we want to have `version` we should sacrifice 1 byte and put just `version` up front, because it's of different nature than `category_id`, `token_format` and `nft_capability`.

The `version` would be set at genesis and be immutable for the whole category. The `token_format` and `nft_capability` are both mutable since outputs can freely take ft & nft in/out of the themselves.

So, this:

`PFX_TOKENS <token_version=0x01> <category_id_32> <token_format | nft_capability> [<nft_commitment_length><nft_commitment>] [ft_amount]`

The purpose of `token_format` is just to tell you what combination of NFT/FT/COMMITMENT is encoded, using 3 bit flags.

**Comment by cculianu** [comment]
> The purpose of https://github.com/bitjson/cashtokens/pull/33 is just to tell you what combination of NFT/FT/COMMITMENT is encoded, using 3 bit flags, it is just a toggle of fields within the format defined for the PFX_TOKEN, 

Ah I see. That's not in the current spec but is coming. Got ya.

> let's not mix it up with serialization/consensus versioning.

LOL! You say this as if right now the line is clearly drawn between serialization and consensus!  See #44  :)  I jest.

> PFX_TOKENS <token_version=0x01> <category_id_32> <token_format | nft_capability> [<nft_commitment_length><nft_commitment>] [ft_amount]

Yeah I mean that would work, of course, and be future-proof.

**Comment by cculianu** [comment]
I'm going to close this issue.  As @A60AB5450353F40E pointed out -- we could always just allocate another codepoint in the future if we really were worried here.

**Comment by A60AB5450353F40E** [comment]
Just to note, TX version field ought to be available for... versioning stuff: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/issues/360
