### ISSUE TITLE
Suggest not adding cashaddr type bits, instead change the prefix to `bch:` to indicate token support.

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#49]
Summary of Suggestion 
---

I suggest we kill two birds with one stone and just change the prefix to `bch:` for mainnet ~~and `tbch:` for testnets and scalenet~~.  ~~Perhaps also `rbch:` for regtest (although we can just leave regtest as `bchreg:` if we wanted to since regtest is not used to send funds to anybody ever.. and if it is, those funds are ephemeral anyway).~~  This in effect allows us to *not* eat up 2 out of 16 type positions for signaling token support.

EDIT: Since testnet coins are "worthless", there is no need to go with `tbch:` for testnet and we should continue to just use `bchtest:` for testnet, to keep things as simple as possible.

Please note that simply changing the prefix string to `bch:` *does* end up affecting how the final address is encoded (since it is used to encode and calculate the checksum).  So it would be sufficient to ensure upgraded software fails to send tokens to un-upgraded software to simply change the prefix.  (We would of course still support the old prefix).

For those worried that changing the prefix is not "harsh" enough:  I believe it really is.  Do note that changing the prefix changes the encoding because the prefix string is used to calculate how the checksum looks.  So a different prefix for the same payload yields a different address string.  Moreover, we can state as a **requirement for the `cashaddr` spec** that the new `bch:` prefix can **only** be used for wallets that are upgraded and are token-aware.  It would be a violation of upgrade9 rules and/or the `cashaddr` spec to deviate from this.

Rationale
---

1. There has been discussion in the past that `bitcoincash:` is too long and `bch:` is far better.  Bitcoin Core went with `bc1:` after all.  Our cashaddress prefix is too huge!!
2.  We only get 4 bits for the type in cashaddr encoding.  That's 16 possible values.  We already use 2 of them for p2sh and p2pkh.  The spec proposes eating up 2 more for token-aware-p2sh and token-aware-p2pkh.  This is 12.5% of the possible remaining values eaten up here.  We only have 12 out of 16 left over.  
3. Technically speaking these aren't new "types".  I believe the intention of the "type" field was not in this spirit.
4. Changing the prefix to indicate token support has the added benefit that it is more human-friendly and naive-one-off-script-friendly.  The changed prefix affects only the last group of 8 characters in the `qp3rsz...` address string.  In this way, it's far easier for humans and for naive software to map the same set of token aware `bch:` and "legacy" `bitcoincash:` addreses to each other.  Even visually you can scan your wallet and notice that basically the same address `qpcal1n...uuvxzprz` is now also starting with `qpcal1n...` and it just has a different suffix.  This is much more "human-friendly" IMHO. (For an example: Consider how `simpleledger:` addresses vs `bitcoincash:` addresses in Electron Cash SLP look almost the same so it's easier on human eyes just scanning their addresses visually).

**Comment by imaginaryusername** [comment]
Note: We might still want (?) a type bit change for P2SH32. It'll also be really nice to specify that the new prefix `bch:` shall only use P2SH32, it's a once in a long while opportunity to break from P2SH20 at no cost to the ecosystem whatsoever _and_ at minimal effort, we should  take it.

**Comment by cculianu** [comment]
@imaginaryusername I don't think we need a type bit *per se* for p2sh32.. There is also a "size" encoding in the lower 4 bits I believe, so it's "obvious" that it's p2sh-32 if the type is p2sh and the size is 32, and not 20.

Now.. on wanting to specify that **only** the new prefix`bch:` shall use p2sh32... Wouldn't that put a burden on wallet devs that **don't** care about supporting token but **do** care about p2sh32 to have to worry about tokens before they can honestly use `bch:`?

**Comment by imaginaryusername** [comment]
I have a hard time imagining any wallet would somehow care enough about p2sh32 (mainly important for complex covenants and other self-perpetuating onchain devices) but not care enough about cashtokens (which greatly simplifies such devices)... at least that's my take. Note that p2sh20 isn't going to be deprecated anytime in forseeable future, and folks who find it acceptable can/should continue using it. 

Having P2SH32 and P2SH20 cross into each other has a downside of end-user confusion: as you said, if p2sh32 is present on `bitcoincash:` old wallet will just interpret it as garbage, which is a problem! Wallet devs and exchanges will be bombarded with questions about "wait you support bitcoincash: addresses, i have one, why doesn't it work??"

vs. If we make a clean break, then it'll be immediately obvious that "new" prefix `bch:` isn't compatible, dramatically lessening the support burden for unupgraded wallets and exchanges.

**Comment by cculianu** [comment]
> Having P2SH32 and P2SH20 cross into each other has a downside of end-user confusion: as you said, if p2sh32 is present on bitcoincash: old wallet will just interpret it as garbage, which is a problem! Wallet devs and exchanges will be bombarded with questions about "wait you support bitcoincash: addresses, i have one, why doesn't it work??"

Hmm. I didn't think about that. Ok, you win. Can specify must support`bch:`  if wanting to use `p2sh32`.

I still do fear some wallets may not care about tokens .. but if you say that a wallet that cares about p2sh32 is very likely to also care about tokens, I believe you.  I have no idea here, tbh.  And the "omfg why is it not working?!?!" argument is a strong one!

**Comment by cculianu** [comment]
This has been implemented for BCHN as an MR:  https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/merge_requests/1595 .  

The plan is that BCHN  won't advertise its own addresses in this format  (because it hasn't yet had code written to manage and send tokens, for example -- so it doesn't "fully support" tokens in the wallet), but it will silently accept this format for sending -- it will able to parse and send funds to addresses in this format.

**Comment by bitjson** [comment]
> There has been discussion in the past that `bitcoincash:` is too long and `bch:` is far better. Bitcoin Core went with bc1: after all. Our cashaddress prefix is too huge!!

This was my initial impression when the CashAddress format was released, but I was convinced that my initial impression was wrong after user testing at BitPay. Here's [the summary of what changed my mind in 2017](https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-November/000525.html). (Note that my initial preference was to change it from `bitcoincash:` to `bch:`.)

In short, there's a real tradeoff here between new users and developers. Developers dislike having to fit more characters into various interfaces, but for new users, there's a real UX difference between (for P2SH32):

1. `bch:qwtcxp42fcp06phz2xec6t5krau0ftew5efy50j9xyfxwa38df40zp58z6t5w`
2. `bitcoincash:qwtcxp42fcp06phz2xec6t5krau0ftew5efy50j9xyfxwa38df40zp58z6t5w`

One of these is a nearly opaque blob for new users. In testing, a lot of users didn't even recognize `bch` as non-random characters, even if they marked in the demographic survey that they are "familiar with Bitcoin Cash (BCH)". This stuck with me because it was not my own experience – I see the `bch`, but there's a huge demographic of non-developers who consider `bch:` to be scary/unrecognizable, but manage to intuitively understand that `bitcoincash:` is the beginning of "an address to receive funds". (I'm sorry I can't seem to find a link to those results on BitPay's website now. If anyone is interested in precise numbers, you could reproduce a study very cheaply with an online user testing service.)

So the `bitcoincash:` prefix is a meaningful UX advantage for non-technical users that I wouldn't be excited to throw away. (And see [the discussion from 2017](https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-November/000525.html) for other reasons `bitcoincash:` was chosen over `bch:`.)

**Comment by cculianu** [comment]
Oh. I see. 

Well @imaginaryusername seems keen on `bch:`. You guys argue it out and let me know what you decide.  I personally prefer the shorter format.  I also dislike adding a new "type" here when maybe these aren't really types at all... (?).

I wonder what other people think, since we are at an impasse it seems on this 1 topic.

**Comment by bitjson** [comment]
It's also worth noting that this change would require all services to update marketing copy, documentation, automated support responses, etc., e.g. searching around quickly, Coinbase has [these](https://help.coinbase.com/en/prime/trading-and-funding/address-formats) [two](https://help.coinbase.com/en/custody/trading-and-funding/address-formatting-standards) support articles, BitPay has [5 articles](https://support.bitpay.com/hc/en-us/search?utf8=%E2%9C%93&query=bitcoincash%3A), and these are just in public-facing documentation. 

These companies will have dozens of additional locations internally (employee knowledge bases, email support macros, etc.) where this sort of description will need to be updated to at least indicated that two formats are possible, e.g. "starting with either `bitcoincash:` or `bch:`", and many locations would require a full description indicating that `bitcoincash:` is an "old" Bitcoin Cash address, and `bch:` is a "new" one. (And some will even have to describe "tokens" to be comprehensive. 😅)

Also, this change likely impacts very important user interfaces in most wallets and services (send/receive), some of which have undergone extensive A/B testing and will be non-trivial to update. A lot of designers are not going to be happy that you're asking them to add a new requirement to those core interfaces.

If this were a change that made Bitcoin Cash work better (especially for new users) I could see how it might be worth the effort, but as far as I can tell, this would make the "public interface" of Bitcoin Cash less friendly to new/casual users while only making it 8 characters-easier for developers.

**Comment by cculianu** [comment]
Well `bch:` will only be used for cashtoken supporting uis/wallets/exchanges. Old format will persist.

UI, dev, and tech doc cost of adding cashtoken support is a huge ocean of cost.  The `bch:` cost would arguably be nothing compared to that...  Remember we specifically specify that to use the `bch:` prefix you MUST support cashtokens and p2sh32... for both receive AND send.. which implies huge UX work anyway, right?

**Comment by bitjson** [comment]
RE: adding new types, I'll copy from https://github.com/bitjson/cashtokens/issues/32#issuecomment-1188122202:

> The CashTokens CHIP would be the first upgrade to reserve new type bits in the CashAddress format since its inception. I'm actually struggling to imagine a more appropriate case to reserve new CashAddress type bits – **if not for tokens, when**?

**Comment by cculianu** [comment]
> 1. `bch:qwtcxp42fcp06phz2xec6t5krau0ftew5efy50j9xyfxwa38df40zp58z6t5w`
> 2. `bitcoincash:qwtcxp42fcp06phz2xec6t5krau0ftew5efy50j9xyfxwa38df40zp58z6t5w`
> One of these is a nearly opaque blob for new users.  ...

If this is a concern can always display in UI as `BCH:qwtcxp42fcp06phz2xec6t5krau0ftew5efy50j9xyfxwa38df40zp58z6t5w`.  Prefix is case-insensitive...

**Comment by imaginaryusername** [comment]
Well, we'll need to weigh new prefix vs type bits by their own merits: if a new prefix is better in all circumstances, then perhaps we should _always_ change prefix instead of type bit. "Having a thing there unused" isn't a good argument, perhaps some methods are just inferior compared to others.

**Comment by cculianu** [comment]
Up until now, the type field encodes how to interpret the hash that is encoded in the address.  Up until now, for the purposes it was always used to decide how to encode the locking script (`scriptPubKey`) for sending.   

I am not sure how strong an argument this is but: From the point of view of BCHN's code (and electron cash's), these aren't strictly speaking "new types" because they yield the exact same locking script... so code that branches on type needs to flatten out 2 types -> 1 type internally.  It's a bit strange to use type in this way, but not overly so..

**Comment by bitjson** [comment]
> Well bch: will only be used for cashtoken supporting uis/wallets/exchanges. Old format will persist and be default for most ppl.

So it's not really even an "old"/"new" upgrade, we'd actually be asking those services to clearly describe the `bch:` prefix as being for "tokens", and they'd likely have to explain what that means, too.

> UI, dev, and tech doc cost of adding cashtoken support is a huge ocean of cost. The `bch:` cost would arguably be nothing but a tiny droplet compared to that... Remember we specifically specify that to use the `bch:` prefix you MUST support cashtokens and p2sh32... for both receive AND send.. which implies huge UX work anyway, right?
carve out a new special type of address

But this work would be forced on all Bitcoin Cash-supporting businesses – right now, every service/wallet in the entire BCH ecosystem supports CashAddress type bits. E.g. [since 2017](https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-November/000525.html), many of BitPay's wallets and interfaces have used the error message: `This Bitcoin Cash address uses an unrecognized version number (X). Please ask the recipient for help using this address.`. Every service/wallet/library must have some similar sort of error message for unsupported versions.

Right now, we place the upgrade burden only on the wallets/services that support CashTokens – they're already going to be adding token support, so it's reasonable for them to update their supporting documentation/macros/etc to inform users whether their address is "token supporting". Most of those interfaces are also going to have some sort of switcher to show an equivalent "non-token supporting" address. If we also change the prefix, we'd be asking every single service/wallet in the ecosystem to at least update their supporting documentation, even if they don't ultimately support CashTokens. That's a much more significant ask than allowing them to use their existing error handling.

**Comment by cculianu** [comment]
> So it's not really even an "old"/"new" upgrade, we'd actually be asking those services to clearly describe the bch: prefix as being for "tokens", and they'd likely have to explain what that means, too.

Hmm. I am not sure.  I do appreciate your looking out for exchange costs, disruption, etc. But the way I see it, an address change implies costs anyway.  

To me a prefix change is easier to explain to people than -- "we support `bitcoincash:` **except** if they start with character `s` or `r`"  (or whatever the new type yields in terms of characters -- I haven't tried it yet).

At some point some exchange somewhere will have to do work either way, though.. won't they?  No matter what we do, work will be generated for people...

> But this work would be forced on all Bitcoin Cash-supporting businesses – right now, every service/wallet in the entire BCH ecosystem supports CashAddress type bits. E.g. [since 2017](https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-November/000525.html), many of BitPay's wallets and interfaces have used the error message: This Bitcoin Cash address uses an unrecognized version number (X). Please ask the recipient for help using this address.. Every service/wallet/library must have some similar sort of error message for unsupported versions.

Hmm so the argument here is that the "type not supported" error path is more commonly handled and more elegantly handled than the "what the fuck is this prefix I don't understand!" Error path?

Either way it's an error path no?  I mean either way people will have to do work.  I am not even convinced either error path is "simpler" for people.. is it?  Maybe in your libauth I guess it might be, no idea.

But either way a rejected address is a rejected address.. like in other software I maintain whether it be the type or the prefix not matching up, the end result is the same really -- a rejection with some error message.

So either way you have to do work to support the new type.    I fail to see this argument.. honestly I do. If you really feel I am missing something please elaborate.

**Comment by imaginaryusername** [comment]
> If we also change the prefix, we'd be asking every single service/wallet in the ecosystem to at least update their supporting documentation, even if they don't ultimately support CashTokens. That's a much more significant ask than allowing them to use their existing error handling.

There are two parts to "error handling": technical and human. The documentation is completely irrelevant to consumers, they're only read by developers and a very small subset of power users, so what you write or don't write in there don't matter when considering support cost. When considering consumers:

Technical: 

  change typebits: Existing error-handling routine. No cost.
  change prefix: incorrect prefix, which is obviously already a routine. No cost.
  
Human:

  change typebits: User gets an uninterpretable "unrecognized version x" error. They almost never get that - most people would've never got it throughout their entire experience with BCH - so they are puzzled at what's wrong. They harass the wallet _and_ the recipient, and it has to be explained at length at both ends.
  
  change prefix: User tries and gets a prefix error. It's immediately obvious to them that `bch:` is something different than what they're used to, so many shrug their shoulders and stop there interpreting (correctly) that they simply got something incompatible. Some ask the recipient or the wallet or both, to which a simple "bch: is incompatible with bitcoincash: " is sufficient.
  
See the difference there?

**Comment by imaginaryusername** [comment]
(Note that this part is not consensus sensitive, so if we strongly disagree on this we can put it off and finalize other parts to keep things on time and in check - working this out in September or October is fine)

**Comment by cculianu** [comment]
> change prefix: User tries and gets a prefix error. It's immediately obvious to them that bch: is something different than what they're used to, so many shrug their shoulders and stop there interpreting (correctly) that they simply got something incompatible. Some ask the recipient or the wallet or both, to which a simple "bch: is incompatible with bitcoincash: " is sufficient.

Yeah, intuitively to me this is the argument that holds the most water, which is why I went with this implementation hard and fast.

**Comment by cculianu** [comment]
> Right now, we place the upgrade burden only on the wallets/services that support CashTokens 

This is not necessarily a true statement.  At the very least, if we introduce a new type **or** a new prefix, some software out there will not understand it.  

You are assuming that if we introduce a new type somehow libs will magically "allow it in", because "it has a type and I know what a type is"..  This is an assumption about how frontends and UIs validate their inputs. And then presumably you are assuming this frontend ultimately just contact a bitcoind RPC and does the equivalent of `sendtoaddress` or something.

if all of the above were true -- then yes, you would be correct.

However I don't think that's how it will work in practice.  I bet you e.e.g coinbase has their own little `cashaddr` implementation and I bet you it barfs immediately on types it doesn't recognize... 

So what I am saying is this statement I am quoting is not true, necessarily, and for it to be true, a lot of assumptions have to hold... which I don't think end up holding in practice.


least, this statement makes an assumption about how exchanges build their software.  You are assuming all software that parses addresses on the front-end

**Comment by bitjson** [comment]
@cculianu

> To me a prefix change is easier to explain to people than -- "we support bitcoincash: except if they start with character s or r" (or whatever the new type yields in terms of characters -- I haven't tried it yet). [...] At some point some exchange somewhere will have to do work either way, though.. won't they? No matter what we do, work will be generated for people...

No, as specified, existing services require no changes. They've already had the opportunity to write whatever error messaging they like for these scenarios, e.g.: `This Bitcoin Cash address uses an unrecognized version number (2). Please ask the recipient for help using this address.`

Whereas a change of prefix yields, at best, their most generic error message, e.g.: `This is not a valid Bitcoin Cash address. Please review the address for errors.`

The first message redirects support requests back to the service that gave the user the CashToken-supporting address, the next will cause many users to contact the support channels of the non-supporting service.

**The CashAddress format promised these services a well-defined upgrade strategy that they've already been required to implement**, but instead of using it, we'd potentially increase their support burden – policy changes like this add a meaningful cost to supporting BCH.

@imaginaryusername 

> change prefix: User tries and gets a prefix error. It's immediately obvious to them that bch: is something different than what they're used to, so many shrug their shoulders and stop there interpreting (correctly) that they simply got something incompatible.

This assumes that the user is an existing, fairly-technical user. Casual and less-technical users are often already frightened by the idea of addresses, and it's risky to assume they'll do any sort of visual inspection upon error, much less that they'll recognize/remember that addresses "normally" have `bitcoincash:` as a prefix.

> Some ask the recipient or the wallet or both, to which a simple "bch: is incompatible with bitcoincash: " is sufficient.

That seems very optimistic. What does "bch: is incompatible with bitcoincash:" mean? Are they different networks? It's still Bitcoin Cash right? Even the word "incompatible" indicates that we're thinking about a more technical audience than the audience of many Bitcoin Cash wallets/services.

---

Again, my initial impression of CashAddresses in 2017 was that `bitcoincash:` should be shortened to `bch:`, but I [changed my mind](https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-November/000525.html) in part because user testing demonstrated I was wrong:

> [...] I also now agree with you that the few extra characters for mainnet (vs a shorter prefix, like `bch:`) are worth it to reduce ambiguity. In fact, this address format is even comprehensible to humans who have never heard
of Bitcoin Cash. I can’t think of any other crypto address formats which accomplish that goal. (What were we thinking before?) [...]

My current take:
- We have an existing, widely-deployed upgrade strategy for CashAddress, and wallets/services may have already carefully written error messages for precisely this scenario.
- Instead of using this system, we'd be creating a new adhoc upgrade strategy that leaves us with an address format that is 8 characters shorter for developers, but less friendly to new users. **We end up with a worse product**.
- We'd also add the technical debt of having two prefixes in common use, indefinitely adding complexity to UIs, supporting documentation, support macros, etc.

Of course, wallets/services can always shorten their representation of addresses by dropping the `bitcoincash:` altogether – **it's designed to be droppable**. But enforcing that UX decision across the ecosystem degrades the experience for new users, and I don't see that as in-scope for this CHIP.

**Comment by zander** [comment]
Heya,

so, when this new format was first introduced for our chain this was pushed by the ABC people and due to timing and stuff we ended up having a discussion about prefix without Amaury. We knew that Amaury wanted to use the 'bcc' prefix at the time, which was seen as a bad idea for various reasons that turned out to be a good call. :rofl: 
I think I was the one that pushed for the readable "bitcoincash" because the extra characters didn't even make the QR code bigger.

A couple of days ago Imaginary did a poll on telegram asking what people would prefer, `bitcoincash` or `bch`, and the result was roughly 50/50. This being from people on telegram hanging out in a BCH channel should say something. Those people are more drained in that abbreviation than the normal user. In the real world that poll would have been smashed by the `bitcoincash` option.

People don't talk about 'USD' or 'EUR', they talk about the full name, not some name traders (which 99% of the users of a currency are not) use.

So this leaves me with two questions;

1. what about instead of 'bch' use `cashtoken:`
2. the statement was made that having only 12 types left is low, can anyone give any indication of what kind of stuff we can expect to fill that up which is apparently not based on what wallets aim to accept.

**Comment by cculianu** [comment]
@bitjson thanks for taking the time to reply again in kind. I’m going to go ahead and also implement the typeid changes as proposed in this spec alongside the other MR I did linked above in these comments.  Either of them are completely independent (for now) of any and all other code changes we are doing for May 2023 so either can be merged eventually.

I’ll try and walk away from being partial to either of them. The more I think about it the more I am starting to “get” your point of view on this and I see it as reasonable.

I’m starting to see the wisdom in that the typeid was intended to handle exactly these situations and that is the canonical upgrade path… that argument to me is gaining weight fwiw.

aesthetically “bch:” seems cleaner but I do see how to some the more verbose form seems nicer and more friendly.

and yea perhaps supporting multiple prefixes is warty from a certain point of view.

not sure. Personally I hate “bitcoincash:” because it’s ugly and long but you and Tom may be right in that most people may find it friendlier and easier.

**Comment by zander** [comment]
> Personally I hate “bitcoincash:” because it’s ugly and long 

The point has always been that it should be optional. You should be able to paste an address without it and it works. But nobody told exchanges about that yet :-(

**Comment by imaginaryusername** [comment]
I'm going to drop my concern too. It will come back to haunt us for many years as a terrible missed opportunity to improve actual UX on the ground, but let's not have that stand in the way of finalizing this spec, which is of much higher importance.

**Comment by imaginaryusername** [comment]
>The point has always been that it should be optional. You should be able to paste an address without it and it works

Over the years it has been increasingly clear that exchanges don't care nearly as much about length as a clear way to indicate which coin the address is for - many newer coins straight up embed their prefixes into their addresses in an unremovable fashion (say, `avax1u09770rudlu2aqmc5963suljndfryfhhrhza7d`, and I've been been informed more than once by folks from the public that it's a very desirable thing.

**Comment by A60AB5450353F40E** [comment]
I voted for `bch:` in that poll, but seeing Jason's arguments I'm now leaning towards `bitcoincash:` which clearly tells you it's a... Bitcoin Cash address :) I'd like to highlight Calin's point that type bits weren't intended to be used just to signal readiness of wallet for some feature but to just tell it what to do with the payload - which doesn't change in case of tokens, the address payload is still converted into P2SH or P2PKH locking bytecode exactly the same way, which is why at first I argued against new address type altogether. So where to squeeze this wallet readiness piece of information?

If we want to use the prefix as version, can't we just append it? `bitcoincash1:`, `bitcoincash2:` ... or `bitcoincash-ct:` or `bitcoincashtokens:`. I don't like `cashtoken:` because it is firstly a Bitcoin Cash address where the wallet signals it can support tokens, but it is still a Bitcoin Cash address, which `cashtoken:` doesn't communicate, what network does `cashtoken` belong to? Note that importing token wallet into non-token wallet and vice versa is generally not a problem (unlike SLP which would likely burn the tokens).

**Comment by cculianu** [comment]
Ok, I implemented the new type=2 and type=3 as suggested in this spec here: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/merge_requests/1596

I'm closing this issue now since it feels like the battle is won by team "new types, no new prefix".
