### ISSUE TITLE
Clarify handling of valid token prefixes mined in transactions prior to activation

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#59]
These all came from my comments as TODOs and I want to enumerate them here. We should make sure the spec _clearly makes the following points_ (if it doesn't already):

- **Standardness changes**. Care must be taken that standardness is respected pre-activation (all PATFOs or even any txn locking script blobs starting with `0xef` should remain non-standard pre-activation).
  - Post-activation, standardness rules change.  Any token-containing input or output is now standard (even PATFOs are now standard, although they fail evaluation later in the pipeline regardless).  Unparseables starting with `0xef` continue to remain non-standard.
- **Failure to parse -> keep bytes in scriptPubKey**. Failure to parse a token should stuff all the bytes in the blob including the leading `0xef` back into the `scriptPubKey`, and `tokenData` should remain null.  (Thus making this output unspendable).
- **BIP69 sorting**. Should specify BIP69 sorting of TX Outs containing token data, sort order **was**:
  - `(a.nValue, a.scriptPubKey) < (b.nValue, b.scriptPubKey)` <-- lexicographical compare
  - It should **become**:
    - `(a.nValue, a.scriptPubKey, a.tokenData) < (b.nValue, b.scriptPubKey, b.tokenData)` <-- lexicographical compare
      - `a.tokenData < b.tokenData` can be expanded  to lex compare as follows:
        - `(a.tokenData.amount, a.tokenData.bitfield, a.tokenData.commitment, a.tokenData.id) < (b.tokenData.amount, b.tokenData.bitfield, b.tokenData.commitment, b.tokenData.id)`

**Comment by bitjson** [comment]
Trying to make sure #58 closes most issues now:

**Standardness changes**: I think this is properly covered now:

> Implementations must recognize otherwise-standard outputs with token prefixes as **standard**. [...]
> Prior to activation, PATFOs remain **nonstandard** but do not invalidate the transaction by consensus. [...]

**Failure to parse**:

I think this note was from before we ironed out all the encoding standardness and PATFOs stuff, but for future readers:

> After activation, any transaction creating an invalid token prefix is itself invalid, and all transactions must pass [Token-Aware Transaction Validation](#token-aware-transaction-validation).

So instead of making invalid token prefixes nonstandard, we make the transaction invalid, and can't even be deliberately mined. That follows our [general strategy for standardness now](https://github.com/bitjson/cashtokens/issues/23) (avoiding creating new cases of non-standardness). It's also slightly less error-prone: there's no reason a user should intentionally create a transaction with an invalid token prefix, since the output would be unspendable and they'll lose the money (and probably burn the tokens they meant to lock too). Making those transactions be non-standard but valid just risks a miner being able to maliciously mine that output and lock-in the user's accident.

---

So with those items solved I think we can close this now in favor of https://github.com/bitjson/cashtokens/issues/51 (an issue specifically for BIP69 sorting). 

Closing, but @cculianu please let me know if we need to do more with those other two items in this issue.

**Comment by cculianu** [comment]
Yes this is correct, and yes BCHN rejects all txns after activation that have token-prefix in outputs (or in inputs) but that don't parse correctly. Correct.

You should specify that not only PATFOs but *all* token-prefix containing txns in either inputs or outputs, pre-activation, should remain non-standard until activation.

**Comment by bitjson** [comment]
> For pre-activation: You should specify that not only PATFOs.. but in fact all token-prefix-containing txns (in either inputs or outputs), should remain non-standard until activation

Ah! Ok this raises a question: as the spec is currently written: 

> **Pre-activation token-forgery outputs (PATFOs)** are transaction outputs mined in blocks prior to activation of this specification where locking bytecode index `0` is set to the `PREFIX_TOKEN` codepoint.

So there's no such thing as a valid token prefix before activation, right? Even if it would pass token validation after activation, it remains unspendable simply because it was mined in a block before activation, and all of those have been explicitly removed from the UTXO set. (Is that how the BCHN implementation works right now?)

<details>
<summary>Thinking through allowing them...</summary>

---

But I suppose it would also be possible to allow previously-mined, otherwise-valid token outputs to be spent, so long as the previously mined transaction passes token-aware validation? That is, it would have to have all valid token outputs, and the tokens it includes would have to have been created from genesis inputs in the transaction (since spending tokens would be invalid before activation). The transaction would have to be intentionally mined since it would have been non-standard, and to support this, nodes would have to dig up the old transaction referenced by the UTXO being spent... (meaning pruned nodes would probably need to just resync...) 

That seems like a lot more work without any significant benefits. I guess it could make initial activation a little smoother – with the current approach, someone could grief by doing a time-warping re-org right after activation time, then "previously mine" any token genesis transactions that people broadcast during the upgrade block, rendering token outputs in those transactions invalid. But after ~10 blocks that attack window closes, and genesis transactions are completely safe on the honest network. (We'll probably create some quick, low-value token transactions in the upgrade block to lock it in, then anyone launching token products would want to wait ~10 blocks to mint their tokens to avoid griefing.)

I don't think we'd even end up with cleaner code after activation, since it's possible to have transactions with some valid and some invalid token outputs (wouldn't pass token validation, so we're back to checking based on activation time).

---

</details>

Anyways: does the CHIP currently match the BCHN implementation? And/or is there a better way to handle valid token prefixes mined in blocks before activation?

Even if we leave it as-is, I should definitely clarify that section of the CHIP with something like `Note: all token outputs included in any transaction mined prior to activation are considered PATFOs, even if the transaction would pass token-aware transaction validation after activation. To be valid, a token output must have been created in a transaction mined after activation.`

**Comment by bitjson** [comment]
(I think the resolution for this issue will also be able to close https://github.com/bitjson/cashtokens/issues/36)

**Comment by cculianu** [comment]
> So there's no such thing as a valid token prefix before activation, right? 

Conceptually no.. but in the details of the code there is a slight difference in that BCHN will yield different error messages for a UTXO that encodes a token correctly pre-activation versus one that doesn't.  But that's an implementation detail.  

They also yield different error messages post-activation should they be (attempted to be) spent.

> Even if it would pass token validation after activation, it remains unspendable simply because it was mined in a block before activation, and all of those have been explicitly removed from the UTXO set. (Is that how the BCHN implementation works right now?)

Correct.

However, we don't remove it from the UTXO set explicitly. They are just rejected as unspendable as a consensus rule (e.g. after activation the code goes -- "a-ha! this is a token! what have we here? A token I see a token it may be. Let me decide if it is a token for theeee..."

But then it looks at the height when it was confirmed and says to itself: "This was created pre-activation, therefore it is DENIED to be spent".  So it's "standard" to have a txn like that, but then it fails consensus anyway so txn is rejected (rejected not for standardness, but as hard-consensus).

Compare that to an unparseable token blob that has TOKEN_PREFIX but doesn't parse correctly, which fails for entirely different reasons... but fails nonetheless.

As to your idea about deletion:  in principle an implementation could just delete those UTXOs as well and the effect would be identical, really, except maybe the error messages would differ. BCHN never deletes UTXOs (except when switching chains on undo)... for "reasons".

> But I suppose it would also be possible to allow previously-mined, otherwise-valid token outputs to be spent, so long as the previously mined transaction passes token-aware validation? 

I don't think it would be readily feasible....  Given that pre-activation one can mine any old thing that contains TOKEN_PREFIX as the first byte, things that would end up violating token consensus invariants and predicates.. let's not go there.  Better to just disallow PATFOs post-activation as that is cleaner and saner.

> Note: all token outputs included in any transaction mined prior to activation are considered PATFOs, even if the transaction would pass token-aware transaction validation after activation. To be valid, a token output must have been created in a transaction mined after activation.

Yes, this matches BCHN and the spec as I understood it and as we talked about with other people like e.g. BitcoinCashAutist and IM-Uname and others.

**Comment by bitjson** [comment]
Thanks for the clarifications @cculianu!

Mind taking a look at https://github.com/bitjson/cashtokens/pull/62 to see if that resolves this?

**Comment by cculianu** [comment]
Yes, #62 looks good.  That resolves this.
