### ISSUE TITLE
About SPECIAL_TOKEN_PREFIX value

### ISSUE THREAD

**Issue by fpelliccioni** [bitjson/cashtokens#76]
Why have you chosen `0xef` for `SPECIAL_TOKEN_PREFIX` ?
Maybe I'm missing something obvious, but couldn't it have been  `0xfe` ?

**Comment by bitjson** [comment]
@fpelliccioni and others talked about this in the BCHN slack, but I'll summarize for anyone finding this later:

We want to reserve the `0xf*` range for multi-byte extensions (may never be required, but doesn't cost much to keep available for now). And otherwise, we want to distance this prefix as far away from the other opcodes as possible (since it's a completely new kind of behavior, and we want to maximize our options for grouping opcodes logically in the future).

(Going to close this now, but feel free to re-open if there's more to discuss here!)

**Comment by bitjson** [comment]
Related: https://github.com/bitjson/cashtokens/issues/76
